// Code generated by ogen, DO NOT EDIT.

package controlplane

// OperationName is the ogen operation name
type OperationName = string

const (
	CheckAuthorizationOperation OperationName = "CheckAuthorization"
	RequestSigninOperation      OperationName = "RequestSignin"
)
