// Code generated by ogen, DO NOT EDIT.

package controlplane

import (
	"fmt"

	"github.com/go-faster/errors"
	"github.com/go-faster/jx"
)

func (s *StatusStatusCode) Error() string {
	return fmt.Sprintf("code %d: %+v", s.StatusCode, s.Response)
}

// The request message for checking authorization given a request ID.
// Ref: #/components/schemas/CheckAuthorizationRequest
type CheckAuthorizationRequest struct {
	// The request ID is a unique identifier for the request.  This is used to
	//  track the request in the system and should be provided by the client.
	RequestID OptString `json:"request_id"`
}

// GetRequestID returns the value of RequestID.
func (s *CheckAuthorizationRequest) GetRequestID() OptString {
	return s.RequestID
}

// SetRequestID sets the value of RequestID.
func (s *CheckAuthorizationRequest) SetRequestID(val OptString) {
	s.RequestID = val
}

// The response message for checking authorization.
// Ref: #/components/schemas/CheckAuthorizationResponse
type CheckAuthorizationResponse struct {
	// The status of the response.
	Status OptCheckAuthorizationResponseStatus `json:"status"`
	// An optional message providing additional information about the response.
	Message OptString `json:"message"`
	// The response data for this request.
	Data OptCheckAuthorizationResponseData `json:"data"`
	// The operation time in microseconds.  This is the time it took to process
	//  the request and generate the response.
	OpTimeUs OptUint64 `json:"op_time_us"`
}

// GetStatus returns the value of Status.
func (s *CheckAuthorizationResponse) GetStatus() OptCheckAuthorizationResponseStatus {
	return s.Status
}

// GetMessage returns the value of Message.
func (s *CheckAuthorizationResponse) GetMessage() OptString {
	return s.Message
}

// GetData returns the value of Data.
func (s *CheckAuthorizationResponse) GetData() OptCheckAuthorizationResponseData {
	return s.Data
}

// GetOpTimeUs returns the value of OpTimeUs.
func (s *CheckAuthorizationResponse) GetOpTimeUs() OptUint64 {
	return s.OpTimeUs
}

// SetStatus sets the value of Status.
func (s *CheckAuthorizationResponse) SetStatus(val OptCheckAuthorizationResponseStatus) {
	s.Status = val
}

// SetMessage sets the value of Message.
func (s *CheckAuthorizationResponse) SetMessage(val OptString) {
	s.Message = val
}

// SetData sets the value of Data.
func (s *CheckAuthorizationResponse) SetData(val OptCheckAuthorizationResponseData) {
	s.Data = val
}

// SetOpTimeUs sets the value of OpTimeUs.
func (s *CheckAuthorizationResponse) SetOpTimeUs(val OptUint64) {
	s.OpTimeUs = val
}

// Ref: #/components/schemas/CheckAuthorizationResponseData
type CheckAuthorizationResponseData struct {
	// The authorization token which can be used to authenticate requests.
	Token OptString `json:"token"`
}

// GetToken returns the value of Token.
func (s *CheckAuthorizationResponseData) GetToken() OptString {
	return s.Token
}

// SetToken sets the value of Token.
func (s *CheckAuthorizationResponseData) SetToken(val OptString) {
	s.Token = val
}

// The status of the response.
type CheckAuthorizationResponseStatus string

const (
	CheckAuthorizationResponseStatusSuccess CheckAuthorizationResponseStatus = "success"
	CheckAuthorizationResponseStatusError   CheckAuthorizationResponseStatus = "error"
)

// AllValues returns all CheckAuthorizationResponseStatus values.
func (CheckAuthorizationResponseStatus) AllValues() []CheckAuthorizationResponseStatus {
	return []CheckAuthorizationResponseStatus{
		CheckAuthorizationResponseStatusSuccess,
		CheckAuthorizationResponseStatusError,
	}
}

// MarshalText implements encoding.TextMarshaler.
func (s CheckAuthorizationResponseStatus) MarshalText() ([]byte, error) {
	switch s {
	case CheckAuthorizationResponseStatusSuccess:
		return []byte(s), nil
	case CheckAuthorizationResponseStatusError:
		return []byte(s), nil
	default:
		return nil, errors.Errorf("invalid value: %q", s)
	}
}

// UnmarshalText implements encoding.TextUnmarshaler.
func (s *CheckAuthorizationResponseStatus) UnmarshalText(data []byte) error {
	switch CheckAuthorizationResponseStatus(data) {
	case CheckAuthorizationResponseStatusSuccess:
		*s = CheckAuthorizationResponseStatusSuccess
		return nil
	case CheckAuthorizationResponseStatusError:
		*s = CheckAuthorizationResponseStatusError
		return nil
	default:
		return errors.Errorf("invalid value: %q", data)
	}
}

// Contains an arbitrary serialized message along with a @type that describes the type of the serialized message.
// Ref: #/components/schemas/GoogleProtobufAny
type GoogleProtobufAny struct {
	// The type of the serialized message.
	Type            OptString `json:"@type"`
	AdditionalProps GoogleProtobufAnyAdditional
}

// GetType returns the value of Type.
func (s *GoogleProtobufAny) GetType() OptString {
	return s.Type
}

// GetAdditionalProps returns the value of AdditionalProps.
func (s *GoogleProtobufAny) GetAdditionalProps() GoogleProtobufAnyAdditional {
	return s.AdditionalProps
}

// SetType sets the value of Type.
func (s *GoogleProtobufAny) SetType(val OptString) {
	s.Type = val
}

// SetAdditionalProps sets the value of AdditionalProps.
func (s *GoogleProtobufAny) SetAdditionalProps(val GoogleProtobufAnyAdditional) {
	s.AdditionalProps = val
}

type GoogleProtobufAnyAdditional map[string]jx.Raw

func (s *GoogleProtobufAnyAdditional) init() GoogleProtobufAnyAdditional {
	m := *s
	if m == nil {
		m = map[string]jx.Raw{}
		*s = m
	}
	return m
}

// NewOptBool returns new OptBool with value set to v.
func NewOptBool(v bool) OptBool {
	return OptBool{
		Value: v,
		Set:   true,
	}
}

// OptBool is optional bool.
type OptBool struct {
	Value bool
	Set   bool
}

// IsSet returns true if OptBool was set.
func (o OptBool) IsSet() bool { return o.Set }

// Reset unsets value.
func (o *OptBool) Reset() {
	var v bool
	o.Value = v
	o.Set = false
}

// SetTo sets value to v.
func (o *OptBool) SetTo(v bool) {
	o.Set = true
	o.Value = v
}

// Get returns value and boolean that denotes whether value was set.
func (o OptBool) Get() (v bool, ok bool) {
	if !o.Set {
		return v, false
	}
	return o.Value, true
}

// Or returns value if set, or given parameter if does not.
func (o OptBool) Or(d bool) bool {
	if v, ok := o.Get(); ok {
		return v
	}
	return d
}

// NewOptCheckAuthorizationResponseData returns new OptCheckAuthorizationResponseData with value set to v.
func NewOptCheckAuthorizationResponseData(v CheckAuthorizationResponseData) OptCheckAuthorizationResponseData {
	return OptCheckAuthorizationResponseData{
		Value: v,
		Set:   true,
	}
}

// OptCheckAuthorizationResponseData is optional CheckAuthorizationResponseData.
type OptCheckAuthorizationResponseData struct {
	Value CheckAuthorizationResponseData
	Set   bool
}

// IsSet returns true if OptCheckAuthorizationResponseData was set.
func (o OptCheckAuthorizationResponseData) IsSet() bool { return o.Set }

// Reset unsets value.
func (o *OptCheckAuthorizationResponseData) Reset() {
	var v CheckAuthorizationResponseData
	o.Value = v
	o.Set = false
}

// SetTo sets value to v.
func (o *OptCheckAuthorizationResponseData) SetTo(v CheckAuthorizationResponseData) {
	o.Set = true
	o.Value = v
}

// Get returns value and boolean that denotes whether value was set.
func (o OptCheckAuthorizationResponseData) Get() (v CheckAuthorizationResponseData, ok bool) {
	if !o.Set {
		return v, false
	}
	return o.Value, true
}

// Or returns value if set, or given parameter if does not.
func (o OptCheckAuthorizationResponseData) Or(d CheckAuthorizationResponseData) CheckAuthorizationResponseData {
	if v, ok := o.Get(); ok {
		return v
	}
	return d
}

// NewOptCheckAuthorizationResponseStatus returns new OptCheckAuthorizationResponseStatus with value set to v.
func NewOptCheckAuthorizationResponseStatus(v CheckAuthorizationResponseStatus) OptCheckAuthorizationResponseStatus {
	return OptCheckAuthorizationResponseStatus{
		Value: v,
		Set:   true,
	}
}

// OptCheckAuthorizationResponseStatus is optional CheckAuthorizationResponseStatus.
type OptCheckAuthorizationResponseStatus struct {
	Value CheckAuthorizationResponseStatus
	Set   bool
}

// IsSet returns true if OptCheckAuthorizationResponseStatus was set.
func (o OptCheckAuthorizationResponseStatus) IsSet() bool { return o.Set }

// Reset unsets value.
func (o *OptCheckAuthorizationResponseStatus) Reset() {
	var v CheckAuthorizationResponseStatus
	o.Value = v
	o.Set = false
}

// SetTo sets value to v.
func (o *OptCheckAuthorizationResponseStatus) SetTo(v CheckAuthorizationResponseStatus) {
	o.Set = true
	o.Value = v
}

// Get returns value and boolean that denotes whether value was set.
func (o OptCheckAuthorizationResponseStatus) Get() (v CheckAuthorizationResponseStatus, ok bool) {
	if !o.Set {
		return v, false
	}
	return o.Value, true
}

// Or returns value if set, or given parameter if does not.
func (o OptCheckAuthorizationResponseStatus) Or(d CheckAuthorizationResponseStatus) CheckAuthorizationResponseStatus {
	if v, ok := o.Get(); ok {
		return v
	}
	return d
}

// NewOptInt32 returns new OptInt32 with value set to v.
func NewOptInt32(v int32) OptInt32 {
	return OptInt32{
		Value: v,
		Set:   true,
	}
}

// OptInt32 is optional int32.
type OptInt32 struct {
	Value int32
	Set   bool
}

// IsSet returns true if OptInt32 was set.
func (o OptInt32) IsSet() bool { return o.Set }

// Reset unsets value.
func (o *OptInt32) Reset() {
	var v int32
	o.Value = v
	o.Set = false
}

// SetTo sets value to v.
func (o *OptInt32) SetTo(v int32) {
	o.Set = true
	o.Value = v
}

// Get returns value and boolean that denotes whether value was set.
func (o OptInt32) Get() (v int32, ok bool) {
	if !o.Set {
		return v, false
	}
	return o.Value, true
}

// Or returns value if set, or given parameter if does not.
func (o OptInt32) Or(d int32) int32 {
	if v, ok := o.Get(); ok {
		return v
	}
	return d
}

// NewOptRequestSigninResponseData returns new OptRequestSigninResponseData with value set to v.
func NewOptRequestSigninResponseData(v RequestSigninResponseData) OptRequestSigninResponseData {
	return OptRequestSigninResponseData{
		Value: v,
		Set:   true,
	}
}

// OptRequestSigninResponseData is optional RequestSigninResponseData.
type OptRequestSigninResponseData struct {
	Value RequestSigninResponseData
	Set   bool
}

// IsSet returns true if OptRequestSigninResponseData was set.
func (o OptRequestSigninResponseData) IsSet() bool { return o.Set }

// Reset unsets value.
func (o *OptRequestSigninResponseData) Reset() {
	var v RequestSigninResponseData
	o.Value = v
	o.Set = false
}

// SetTo sets value to v.
func (o *OptRequestSigninResponseData) SetTo(v RequestSigninResponseData) {
	o.Set = true
	o.Value = v
}

// Get returns value and boolean that denotes whether value was set.
func (o OptRequestSigninResponseData) Get() (v RequestSigninResponseData, ok bool) {
	if !o.Set {
		return v, false
	}
	return o.Value, true
}

// Or returns value if set, or given parameter if does not.
func (o OptRequestSigninResponseData) Or(d RequestSigninResponseData) RequestSigninResponseData {
	if v, ok := o.Get(); ok {
		return v
	}
	return d
}

// NewOptRequestSigninResponseStatus returns new OptRequestSigninResponseStatus with value set to v.
func NewOptRequestSigninResponseStatus(v RequestSigninResponseStatus) OptRequestSigninResponseStatus {
	return OptRequestSigninResponseStatus{
		Value: v,
		Set:   true,
	}
}

// OptRequestSigninResponseStatus is optional RequestSigninResponseStatus.
type OptRequestSigninResponseStatus struct {
	Value RequestSigninResponseStatus
	Set   bool
}

// IsSet returns true if OptRequestSigninResponseStatus was set.
func (o OptRequestSigninResponseStatus) IsSet() bool { return o.Set }

// Reset unsets value.
func (o *OptRequestSigninResponseStatus) Reset() {
	var v RequestSigninResponseStatus
	o.Value = v
	o.Set = false
}

// SetTo sets value to v.
func (o *OptRequestSigninResponseStatus) SetTo(v RequestSigninResponseStatus) {
	o.Set = true
	o.Value = v
}

// Get returns value and boolean that denotes whether value was set.
func (o OptRequestSigninResponseStatus) Get() (v RequestSigninResponseStatus, ok bool) {
	if !o.Set {
		return v, false
	}
	return o.Value, true
}

// Or returns value if set, or given parameter if does not.
func (o OptRequestSigninResponseStatus) Or(d RequestSigninResponseStatus) RequestSigninResponseStatus {
	if v, ok := o.Get(); ok {
		return v
	}
	return d
}

// NewOptString returns new OptString with value set to v.
func NewOptString(v string) OptString {
	return OptString{
		Value: v,
		Set:   true,
	}
}

// OptString is optional string.
type OptString struct {
	Value string
	Set   bool
}

// IsSet returns true if OptString was set.
func (o OptString) IsSet() bool { return o.Set }

// Reset unsets value.
func (o *OptString) Reset() {
	var v string
	o.Value = v
	o.Set = false
}

// SetTo sets value to v.
func (o *OptString) SetTo(v string) {
	o.Set = true
	o.Value = v
}

// Get returns value and boolean that denotes whether value was set.
func (o OptString) Get() (v string, ok bool) {
	if !o.Set {
		return v, false
	}
	return o.Value, true
}

// Or returns value if set, or given parameter if does not.
func (o OptString) Or(d string) string {
	if v, ok := o.Get(); ok {
		return v
	}
	return d
}

// NewOptUint64 returns new OptUint64 with value set to v.
func NewOptUint64(v uint64) OptUint64 {
	return OptUint64{
		Value: v,
		Set:   true,
	}
}

// OptUint64 is optional uint64.
type OptUint64 struct {
	Value uint64
	Set   bool
}

// IsSet returns true if OptUint64 was set.
func (o OptUint64) IsSet() bool { return o.Set }

// Reset unsets value.
func (o *OptUint64) Reset() {
	var v uint64
	o.Value = v
	o.Set = false
}

// SetTo sets value to v.
func (o *OptUint64) SetTo(v uint64) {
	o.Set = true
	o.Value = v
}

// Get returns value and boolean that denotes whether value was set.
func (o OptUint64) Get() (v uint64, ok bool) {
	if !o.Set {
		return v, false
	}
	return o.Value, true
}

// Or returns value if set, or given parameter if does not.
func (o OptUint64) Or(d uint64) uint64 {
	if v, ok := o.Get(); ok {
		return v
	}
	return d
}

// The request message for a sign-in request.
// Ref: #/components/schemas/RequestSigninRequest
type RequestSigninRequest struct {
	// The hostname is the name of the machine making the request.  This is
	//  mandatory as it consitutes a unique identifier for the machine.
	Hostname OptString `json:"hostname"`
	// The operating system of the machine making the request.
	Os OptString `json:"os"`
	// The version of the operating system of the machine making the request, if
	//  available.
	//
	//  For Android, it's like "10", "11", "12", etc.  For iOS and macOS it's like
	//  "15.6.1" or "12.4.0".  For Windows it's like "10.0.19044.1889". For FreeBSD
	//  it's like "12.3-STABLE".  For Linux, this is simply the kernel version on
	//  Linux, like "5.10.0-17-amd64".
	OsVersion OptString `json:"os_version"`
	// A best-effort whether the client is running in a container.
	Container OptBool `json:"container"`
	// The OS distribution, if known.  E.g. "debian", "ubuntu", "nixos", ...
	Distro OptString `json:"distro"`
	// The OS distribution version if known.  E.g. "20.04", ...
	DistroVersion OptString `json:"distro_version"`
	// THe OS distribution codename if known.  E.g. "jammy", "bullseye", ...
	DistroCodename OptString `json:"distro_codename"`
	// The CLI version is the version of the Unikraft CLI that is making the
	//  request.
	CliVersion OptString `json:"cli_version"`
	// If available, the GOARCH value (of the built binary).
	Goarch OptString `json:"goarch"`
	// If available, the GOOS value (of the built binary)
	Goos OptString `json:"goos"`
	// if available, the Go version binary was built with.
	GoVersion OptString `json:"go_version"`
}

// GetHostname returns the value of Hostname.
func (s *RequestSigninRequest) GetHostname() OptString {
	return s.Hostname
}

// GetOs returns the value of Os.
func (s *RequestSigninRequest) GetOs() OptString {
	return s.Os
}

// GetOsVersion returns the value of OsVersion.
func (s *RequestSigninRequest) GetOsVersion() OptString {
	return s.OsVersion
}

// GetContainer returns the value of Container.
func (s *RequestSigninRequest) GetContainer() OptBool {
	return s.Container
}

// GetDistro returns the value of Distro.
func (s *RequestSigninRequest) GetDistro() OptString {
	return s.Distro
}

// GetDistroVersion returns the value of DistroVersion.
func (s *RequestSigninRequest) GetDistroVersion() OptString {
	return s.DistroVersion
}

// GetDistroCodename returns the value of DistroCodename.
func (s *RequestSigninRequest) GetDistroCodename() OptString {
	return s.DistroCodename
}

// GetCliVersion returns the value of CliVersion.
func (s *RequestSigninRequest) GetCliVersion() OptString {
	return s.CliVersion
}

// GetGoarch returns the value of Goarch.
func (s *RequestSigninRequest) GetGoarch() OptString {
	return s.Goarch
}

// GetGoos returns the value of Goos.
func (s *RequestSigninRequest) GetGoos() OptString {
	return s.Goos
}

// GetGoVersion returns the value of GoVersion.
func (s *RequestSigninRequest) GetGoVersion() OptString {
	return s.GoVersion
}

// SetHostname sets the value of Hostname.
func (s *RequestSigninRequest) SetHostname(val OptString) {
	s.Hostname = val
}

// SetOs sets the value of Os.
func (s *RequestSigninRequest) SetOs(val OptString) {
	s.Os = val
}

// SetOsVersion sets the value of OsVersion.
func (s *RequestSigninRequest) SetOsVersion(val OptString) {
	s.OsVersion = val
}

// SetContainer sets the value of Container.
func (s *RequestSigninRequest) SetContainer(val OptBool) {
	s.Container = val
}

// SetDistro sets the value of Distro.
func (s *RequestSigninRequest) SetDistro(val OptString) {
	s.Distro = val
}

// SetDistroVersion sets the value of DistroVersion.
func (s *RequestSigninRequest) SetDistroVersion(val OptString) {
	s.DistroVersion = val
}

// SetDistroCodename sets the value of DistroCodename.
func (s *RequestSigninRequest) SetDistroCodename(val OptString) {
	s.DistroCodename = val
}

// SetCliVersion sets the value of CliVersion.
func (s *RequestSigninRequest) SetCliVersion(val OptString) {
	s.CliVersion = val
}

// SetGoarch sets the value of Goarch.
func (s *RequestSigninRequest) SetGoarch(val OptString) {
	s.Goarch = val
}

// SetGoos sets the value of Goos.
func (s *RequestSigninRequest) SetGoos(val OptString) {
	s.Goos = val
}

// SetGoVersion sets the value of GoVersion.
func (s *RequestSigninRequest) SetGoVersion(val OptString) {
	s.GoVersion = val
}

// The response message for a sign-in request.
// Ref: #/components/schemas/RequestSigninResponse
type RequestSigninResponse struct {
	// The status of the response.
	Status OptRequestSigninResponseStatus `json:"status"`
	// An optional message providing additional information about the response.
	Message OptString `json:"message"`
	// The response data for this request.
	Data OptRequestSigninResponseData `json:"data"`
	// The operation time in microseconds.  This is the time it took to process
	//  the request and generate the response.
	OpTimeUs OptUint64 `json:"op_time_us"`
}

// GetStatus returns the value of Status.
func (s *RequestSigninResponse) GetStatus() OptRequestSigninResponseStatus {
	return s.Status
}

// GetMessage returns the value of Message.
func (s *RequestSigninResponse) GetMessage() OptString {
	return s.Message
}

// GetData returns the value of Data.
func (s *RequestSigninResponse) GetData() OptRequestSigninResponseData {
	return s.Data
}

// GetOpTimeUs returns the value of OpTimeUs.
func (s *RequestSigninResponse) GetOpTimeUs() OptUint64 {
	return s.OpTimeUs
}

// SetStatus sets the value of Status.
func (s *RequestSigninResponse) SetStatus(val OptRequestSigninResponseStatus) {
	s.Status = val
}

// SetMessage sets the value of Message.
func (s *RequestSigninResponse) SetMessage(val OptString) {
	s.Message = val
}

// SetData sets the value of Data.
func (s *RequestSigninResponse) SetData(val OptRequestSigninResponseData) {
	s.Data = val
}

// SetOpTimeUs sets the value of OpTimeUs.
func (s *RequestSigninResponse) SetOpTimeUs(val OptUint64) {
	s.OpTimeUs = val
}

// Ref: #/components/schemas/RequestSigninResponseData
type RequestSigninResponseData struct {
	// The full URL which can be used to remotely confirm the signin.
	AuthorizationURL OptString `json:"authorization_url"`
	// A unique identifier for the request.  This can be used to track the
	//  request in the system.
	RequestID OptString `json:"request_id"`
}

// GetAuthorizationURL returns the value of AuthorizationURL.
func (s *RequestSigninResponseData) GetAuthorizationURL() OptString {
	return s.AuthorizationURL
}

// GetRequestID returns the value of RequestID.
func (s *RequestSigninResponseData) GetRequestID() OptString {
	return s.RequestID
}

// SetAuthorizationURL sets the value of AuthorizationURL.
func (s *RequestSigninResponseData) SetAuthorizationURL(val OptString) {
	s.AuthorizationURL = val
}

// SetRequestID sets the value of RequestID.
func (s *RequestSigninResponseData) SetRequestID(val OptString) {
	s.RequestID = val
}

// The status of the response.
type RequestSigninResponseStatus string

const (
	RequestSigninResponseStatusSuccess RequestSigninResponseStatus = "success"
	RequestSigninResponseStatusError   RequestSigninResponseStatus = "error"
)

// AllValues returns all RequestSigninResponseStatus values.
func (RequestSigninResponseStatus) AllValues() []RequestSigninResponseStatus {
	return []RequestSigninResponseStatus{
		RequestSigninResponseStatusSuccess,
		RequestSigninResponseStatusError,
	}
}

// MarshalText implements encoding.TextMarshaler.
func (s RequestSigninResponseStatus) MarshalText() ([]byte, error) {
	switch s {
	case RequestSigninResponseStatusSuccess:
		return []byte(s), nil
	case RequestSigninResponseStatusError:
		return []byte(s), nil
	default:
		return nil, errors.Errorf("invalid value: %q", s)
	}
}

// UnmarshalText implements encoding.TextUnmarshaler.
func (s *RequestSigninResponseStatus) UnmarshalText(data []byte) error {
	switch RequestSigninResponseStatus(data) {
	case RequestSigninResponseStatusSuccess:
		*s = RequestSigninResponseStatusSuccess
		return nil
	case RequestSigninResponseStatusError:
		*s = RequestSigninResponseStatusError
		return nil
	default:
		return errors.Errorf("invalid value: %q", data)
	}
}

// The `Status` type defines a logical error model that is suitable for different programming environments, including REST APIs and RPC APIs. It is used by [gRPC](https://github.com/grpc). Each `Status` message contains three pieces of data: error code, error message, and error details. You can find out more about this error model and how to work with it in the [API Design Guide](https://cloud.google.com/apis/design/errors).
// Ref: #/components/schemas/Status
type Status struct {
	// The status code, which should be an enum value of [google.rpc.Code][google.rpc.Code].
	Code OptInt32 `json:"code"`
	// A developer-facing error message, which should be in English. Any user-facing error message should be localized and sent in the [google.rpc.Status.details][google.rpc.Status.details] field, or localized by the client.
	Message OptString `json:"message"`
	// A list of messages that carry the error details.  There is a common set of message types for APIs to use.
	Details []GoogleProtobufAny `json:"details"`
}

// GetCode returns the value of Code.
func (s *Status) GetCode() OptInt32 {
	return s.Code
}

// GetMessage returns the value of Message.
func (s *Status) GetMessage() OptString {
	return s.Message
}

// GetDetails returns the value of Details.
func (s *Status) GetDetails() []GoogleProtobufAny {
	return s.Details
}

// SetCode sets the value of Code.
func (s *Status) SetCode(val OptInt32) {
	s.Code = val
}

// SetMessage sets the value of Message.
func (s *Status) SetMessage(val OptString) {
	s.Message = val
}

// SetDetails sets the value of Details.
func (s *Status) SetDetails(val []GoogleProtobufAny) {
	s.Details = val
}

// StatusStatusCode wraps Status with StatusCode.
type StatusStatusCode struct {
	StatusCode int
	Response   Status
}

// GetStatusCode returns the value of StatusCode.
func (s *StatusStatusCode) GetStatusCode() int {
	return s.StatusCode
}

// GetResponse returns the value of Response.
func (s *StatusStatusCode) GetResponse() Status {
	return s.Response
}

// SetStatusCode sets the value of StatusCode.
func (s *StatusStatusCode) SetStatusCode(val int) {
	s.StatusCode = val
}

// SetResponse sets the value of Response.
func (s *StatusStatusCode) SetResponse(val Status) {
	s.Response = val
}
