// Code generated by ogen, DO NOT EDIT.

package controlplane

// SigninParams is parameters of Signin operation.
type SigninParams struct {
	// The CLI version is the version of the Unikraft CLI that is making the
	//  request.
	CliVersion OptString
	// The operating system of the machine making the request.
	Os OptString
	// The hostname is the name of the machine making the request.
	Hostname OptString
}
