// Code generated by ogen, DO NOT EDIT.

package controlplane

import (
	"context"
	"net/url"
	"strings"

	"github.com/go-faster/errors"

	ht "github.com/ogen-go/ogen/http"
	"github.com/ogen-go/ogen/uri"
)

func trimTrailingSlashes(u *url.URL) {
	u.Path = strings.TrimRight(u.Path, "/")
	u.RawPath = strings.TrimRight(u.RawPath, "/")
}

// Invoker invokes operations described by OpenAPI v3 specification.
type Invoker interface {
	// CheckAuthorization invokes CheckAuthorization operation.
	//
	// CheckAuthorization is used to check the authorization status of a request.
	//  It streams responses back to the client, indicating whether the signin
	//  request is authorized or not.
	//
	// POST /v1/auth/check
	CheckAuthorization(ctx context.Context, request *CheckAuthorizationRequest) (*CheckAuthorizationResponse, error)
	// RequestSignin invokes RequestSignin operation.
	//
	// RequestSignin initiates the sign-in process and returns an authorization
	//  URL.  The user should be redirected to this URL to complete the sign-in.
	//
	// POST /v1/auth/signin
	RequestSignin(ctx context.Context, request *RequestSigninRequest) (*RequestSigninResponse, error)
}

// Client implements OAS client.
type Client struct {
	serverURL *url.URL
	baseClient
}

// NewClient initializes new Client defined by OAS.
func NewClient(serverURL string, opts ...ClientOption) (*Client, error) {
	u, err := url.Parse(serverURL)
	if err != nil {
		return nil, err
	}
	trimTrailingSlashes(u)

	c, err := newClientConfig(opts...).baseClient()
	if err != nil {
		return nil, err
	}
	return &Client{
		serverURL:  u,
		baseClient: c,
	}, nil
}

type serverURLKey struct{}

// WithServerURL sets context key to override server URL.
func WithServerURL(ctx context.Context, u *url.URL) context.Context {
	return context.WithValue(ctx, serverURLKey{}, u)
}

func (c *Client) requestURL(ctx context.Context) *url.URL {
	u, ok := ctx.Value(serverURLKey{}).(*url.URL)
	if !ok {
		return c.serverURL
	}
	return u
}

// CheckAuthorization invokes CheckAuthorization operation.
//
// CheckAuthorization is used to check the authorization status of a request.
//
//	It streams responses back to the client, indicating whether the signin
//	request is authorized or not.
//
// POST /v1/auth/check
func (c *Client) CheckAuthorization(ctx context.Context, request *CheckAuthorizationRequest) (*CheckAuthorizationResponse, error) {
	res, err := c.sendCheckAuthorization(ctx, request)
	return res, err
}

func (c *Client) sendCheckAuthorization(ctx context.Context, request *CheckAuthorizationRequest) (res *CheckAuthorizationResponse, err error) {

	u := uri.Clone(c.requestURL(ctx))
	var pathParts [1]string
	pathParts[0] = "/v1/auth/check"
	uri.AddPathParts(u, pathParts[:]...)

	r, err := ht.NewRequest(ctx, "POST", u)
	if err != nil {
		return res, errors.Wrap(err, "create request")
	}
	if err := encodeCheckAuthorizationRequest(request, r); err != nil {
		return res, errors.Wrap(err, "encode request")
	}

	resp, err := c.cfg.Client.Do(r)
	if err != nil {
		return res, errors.Wrap(err, "do request")
	}

	defer resp.Body.Close()

	result, err := decodeCheckAuthorizationResponse(resp)
	if err != nil {
		return res, errors.Wrap(err, "decode response")
	}

	return result, nil
}

// RequestSignin invokes RequestSignin operation.
//
// RequestSignin initiates the sign-in process and returns an authorization
//
//	URL.  The user should be redirected to this URL to complete the sign-in.
//
// POST /v1/auth/signin
func (c *Client) RequestSignin(ctx context.Context, request *RequestSigninRequest) (*RequestSigninResponse, error) {
	res, err := c.sendRequestSignin(ctx, request)
	return res, err
}

func (c *Client) sendRequestSignin(ctx context.Context, request *RequestSigninRequest) (res *RequestSigninResponse, err error) {

	u := uri.Clone(c.requestURL(ctx))
	var pathParts [1]string
	pathParts[0] = "/v1/auth/signin"
	uri.AddPathParts(u, pathParts[:]...)

	r, err := ht.NewRequest(ctx, "POST", u)
	if err != nil {
		return res, errors.Wrap(err, "create request")
	}
	if err := encodeRequestSigninRequest(request, r); err != nil {
		return res, errors.Wrap(err, "encode request")
	}

	resp, err := c.cfg.Client.Do(r)
	if err != nil {
		return res, errors.Wrap(err, "do request")
	}

	defer resp.Body.Close()

	result, err := decodeRequestSigninResponse(resp)
	if err != nil {
		return res, errors.Wrap(err, "decode response")
	}

	return result, nil
}
