// Code generated by ogen, DO NOT EDIT.

package controlplane

import (
	"fmt"

	"github.com/go-faster/errors"
	"github.com/go-faster/jx"
)

func (s *StatusStatusCode) Error() string {
	return fmt.Sprintf("code %d: %+v", s.StatusCode, s.Response)
}

// Contains an arbitrary serialized message along with a @type that describes the type of the serialized message.
// Ref: #/components/schemas/GoogleProtobufAny
type GoogleProtobufAny struct {
	// The type of the serialized message.
	Type            OptString `json:"@type"`
	AdditionalProps GoogleProtobufAnyAdditional
}

// GetType returns the value of Type.
func (s *GoogleProtobufAny) GetType() OptString {
	return s.Type
}

// GetAdditionalProps returns the value of AdditionalProps.
func (s *GoogleProtobufAny) GetAdditionalProps() GoogleProtobufAnyAdditional {
	return s.AdditionalProps
}

// SetType sets the value of Type.
func (s *GoogleProtobufAny) SetType(val OptString) {
	s.Type = val
}

// SetAdditionalProps sets the value of AdditionalProps.
func (s *GoogleProtobufAny) SetAdditionalProps(val GoogleProtobufAnyAdditional) {
	s.AdditionalProps = val
}

type GoogleProtobufAnyAdditional map[string]jx.Raw

func (s *GoogleProtobufAnyAdditional) init() GoogleProtobufAnyAdditional {
	m := *s
	if m == nil {
		m = map[string]jx.Raw{}
		*s = m
	}
	return m
}

// NewOptBool returns new OptBool with value set to v.
func NewOptBool(v bool) OptBool {
	return OptBool{
		Value: v,
		Set:   true,
	}
}

// OptBool is optional bool.
type OptBool struct {
	Value bool
	Set   bool
}

// IsSet returns true if OptBool was set.
func (o OptBool) IsSet() bool { return o.Set }

// Reset unsets value.
func (o *OptBool) Reset() {
	var v bool
	o.Value = v
	o.Set = false
}

// SetTo sets value to v.
func (o *OptBool) SetTo(v bool) {
	o.Set = true
	o.Value = v
}

// Get returns value and boolean that denotes whether value was set.
func (o OptBool) Get() (v bool, ok bool) {
	if !o.Set {
		return v, false
	}
	return o.Value, true
}

// Or returns value if set, or given parameter if does not.
func (o OptBool) Or(d bool) bool {
	if v, ok := o.Get(); ok {
		return v
	}
	return d
}

// NewOptInt32 returns new OptInt32 with value set to v.
func NewOptInt32(v int32) OptInt32 {
	return OptInt32{
		Value: v,
		Set:   true,
	}
}

// OptInt32 is optional int32.
type OptInt32 struct {
	Value int32
	Set   bool
}

// IsSet returns true if OptInt32 was set.
func (o OptInt32) IsSet() bool { return o.Set }

// Reset unsets value.
func (o *OptInt32) Reset() {
	var v int32
	o.Value = v
	o.Set = false
}

// SetTo sets value to v.
func (o *OptInt32) SetTo(v int32) {
	o.Set = true
	o.Value = v
}

// Get returns value and boolean that denotes whether value was set.
func (o OptInt32) Get() (v int32, ok bool) {
	if !o.Set {
		return v, false
	}
	return o.Value, true
}

// Or returns value if set, or given parameter if does not.
func (o OptInt32) Or(d int32) int32 {
	if v, ok := o.Get(); ok {
		return v
	}
	return d
}

// NewOptSigninResponseData returns new OptSigninResponseData with value set to v.
func NewOptSigninResponseData(v SigninResponseData) OptSigninResponseData {
	return OptSigninResponseData{
		Value: v,
		Set:   true,
	}
}

// OptSigninResponseData is optional SigninResponseData.
type OptSigninResponseData struct {
	Value SigninResponseData
	Set   bool
}

// IsSet returns true if OptSigninResponseData was set.
func (o OptSigninResponseData) IsSet() bool { return o.Set }

// Reset unsets value.
func (o *OptSigninResponseData) Reset() {
	var v SigninResponseData
	o.Value = v
	o.Set = false
}

// SetTo sets value to v.
func (o *OptSigninResponseData) SetTo(v SigninResponseData) {
	o.Set = true
	o.Value = v
}

// Get returns value and boolean that denotes whether value was set.
func (o OptSigninResponseData) Get() (v SigninResponseData, ok bool) {
	if !o.Set {
		return v, false
	}
	return o.Value, true
}

// Or returns value if set, or given parameter if does not.
func (o OptSigninResponseData) Or(d SigninResponseData) SigninResponseData {
	if v, ok := o.Get(); ok {
		return v
	}
	return d
}

// NewOptSigninResponseStatus returns new OptSigninResponseStatus with value set to v.
func NewOptSigninResponseStatus(v SigninResponseStatus) OptSigninResponseStatus {
	return OptSigninResponseStatus{
		Value: v,
		Set:   true,
	}
}

// OptSigninResponseStatus is optional SigninResponseStatus.
type OptSigninResponseStatus struct {
	Value SigninResponseStatus
	Set   bool
}

// IsSet returns true if OptSigninResponseStatus was set.
func (o OptSigninResponseStatus) IsSet() bool { return o.Set }

// Reset unsets value.
func (o *OptSigninResponseStatus) Reset() {
	var v SigninResponseStatus
	o.Value = v
	o.Set = false
}

// SetTo sets value to v.
func (o *OptSigninResponseStatus) SetTo(v SigninResponseStatus) {
	o.Set = true
	o.Value = v
}

// Get returns value and boolean that denotes whether value was set.
func (o OptSigninResponseStatus) Get() (v SigninResponseStatus, ok bool) {
	if !o.Set {
		return v, false
	}
	return o.Value, true
}

// Or returns value if set, or given parameter if does not.
func (o OptSigninResponseStatus) Or(d SigninResponseStatus) SigninResponseStatus {
	if v, ok := o.Get(); ok {
		return v
	}
	return d
}

// NewOptString returns new OptString with value set to v.
func NewOptString(v string) OptString {
	return OptString{
		Value: v,
		Set:   true,
	}
}

// OptString is optional string.
type OptString struct {
	Value string
	Set   bool
}

// IsSet returns true if OptString was set.
func (o OptString) IsSet() bool { return o.Set }

// Reset unsets value.
func (o *OptString) Reset() {
	var v string
	o.Value = v
	o.Set = false
}

// SetTo sets value to v.
func (o *OptString) SetTo(v string) {
	o.Set = true
	o.Value = v
}

// Get returns value and boolean that denotes whether value was set.
func (o OptString) Get() (v string, ok bool) {
	if !o.Set {
		return v, false
	}
	return o.Value, true
}

// Or returns value if set, or given parameter if does not.
func (o OptString) Or(d string) string {
	if v, ok := o.Get(); ok {
		return v
	}
	return d
}

// NewOptUint64 returns new OptUint64 with value set to v.
func NewOptUint64(v uint64) OptUint64 {
	return OptUint64{
		Value: v,
		Set:   true,
	}
}

// OptUint64 is optional uint64.
type OptUint64 struct {
	Value uint64
	Set   bool
}

// IsSet returns true if OptUint64 was set.
func (o OptUint64) IsSet() bool { return o.Set }

// Reset unsets value.
func (o *OptUint64) Reset() {
	var v uint64
	o.Value = v
	o.Set = false
}

// SetTo sets value to v.
func (o *OptUint64) SetTo(v uint64) {
	o.Set = true
	o.Value = v
}

// Get returns value and boolean that denotes whether value was set.
func (o OptUint64) Get() (v uint64, ok bool) {
	if !o.Set {
		return v, false
	}
	return o.Value, true
}

// Or returns value if set, or given parameter if does not.
func (o OptUint64) Or(d uint64) uint64 {
	if v, ok := o.Get(); ok {
		return v
	}
	return d
}

// The request message for a sign-in request.
// Ref: #/components/schemas/SigninRequest
type SigninRequest struct {
	// The hostname is the name of the machine making the request.  This is
	//  mandatory as it consitutes a unique identifier for the machine.
	Hostname OptString `json:"hostname"`
	// The operating system of the machine making the request.
	Os OptString `json:"os"`
	// The version of the operating system of the machine making the request, if
	//  available.
	//
	//  For Android, it's like "10", "11", "12", etc.  For iOS and macOS it's like
	//  "15.6.1" or "12.4.0".  For Windows it's like "10.0.19044.1889". For FreeBSD
	//  it's like "12.3-STABLE".  For Linux, this is simply the kernel version on
	//  Linux, like "5.10.0-17-amd64".
	OsVersion OptString `json:"os_version"`
	// A best-effort whether the client is running in a container.
	Container OptBool `json:"container"`
	// The OS distribution, if known.  E.g. "debian", "ubuntu", "nixos", ...
	Distro OptString `json:"distro"`
	// The OS distribution version if known.  E.g. "20.04", ...
	DistroVersion OptString `json:"distro_version"`
	// THe OS distribution codename if known.  E.g. "jammy", "bullseye", ...
	DistroCodename OptString `json:"distro_codename"`
	// The CLI version is the version of the Unikraft CLI that is making the
	//  request.
	CliVersion OptString `json:"cli_version"`
	// If available, the GOARCH value (of the built binary).
	Goarch OptString `json:"goarch"`
	// If available, the GOOS value (of the built binary)
	Goos OptString `json:"goos"`
	// if available, the Go version binary was built with.
	GoVersion OptString `json:"go_version"`
}

// GetHostname returns the value of Hostname.
func (s *SigninRequest) GetHostname() OptString {
	return s.Hostname
}

// GetOs returns the value of Os.
func (s *SigninRequest) GetOs() OptString {
	return s.Os
}

// GetOsVersion returns the value of OsVersion.
func (s *SigninRequest) GetOsVersion() OptString {
	return s.OsVersion
}

// GetContainer returns the value of Container.
func (s *SigninRequest) GetContainer() OptBool {
	return s.Container
}

// GetDistro returns the value of Distro.
func (s *SigninRequest) GetDistro() OptString {
	return s.Distro
}

// GetDistroVersion returns the value of DistroVersion.
func (s *SigninRequest) GetDistroVersion() OptString {
	return s.DistroVersion
}

// GetDistroCodename returns the value of DistroCodename.
func (s *SigninRequest) GetDistroCodename() OptString {
	return s.DistroCodename
}

// GetCliVersion returns the value of CliVersion.
func (s *SigninRequest) GetCliVersion() OptString {
	return s.CliVersion
}

// GetGoarch returns the value of Goarch.
func (s *SigninRequest) GetGoarch() OptString {
	return s.Goarch
}

// GetGoos returns the value of Goos.
func (s *SigninRequest) GetGoos() OptString {
	return s.Goos
}

// GetGoVersion returns the value of GoVersion.
func (s *SigninRequest) GetGoVersion() OptString {
	return s.GoVersion
}

// SetHostname sets the value of Hostname.
func (s *SigninRequest) SetHostname(val OptString) {
	s.Hostname = val
}

// SetOs sets the value of Os.
func (s *SigninRequest) SetOs(val OptString) {
	s.Os = val
}

// SetOsVersion sets the value of OsVersion.
func (s *SigninRequest) SetOsVersion(val OptString) {
	s.OsVersion = val
}

// SetContainer sets the value of Container.
func (s *SigninRequest) SetContainer(val OptBool) {
	s.Container = val
}

// SetDistro sets the value of Distro.
func (s *SigninRequest) SetDistro(val OptString) {
	s.Distro = val
}

// SetDistroVersion sets the value of DistroVersion.
func (s *SigninRequest) SetDistroVersion(val OptString) {
	s.DistroVersion = val
}

// SetDistroCodename sets the value of DistroCodename.
func (s *SigninRequest) SetDistroCodename(val OptString) {
	s.DistroCodename = val
}

// SetCliVersion sets the value of CliVersion.
func (s *SigninRequest) SetCliVersion(val OptString) {
	s.CliVersion = val
}

// SetGoarch sets the value of Goarch.
func (s *SigninRequest) SetGoarch(val OptString) {
	s.Goarch = val
}

// SetGoos sets the value of Goos.
func (s *SigninRequest) SetGoos(val OptString) {
	s.Goos = val
}

// SetGoVersion sets the value of GoVersion.
func (s *SigninRequest) SetGoVersion(val OptString) {
	s.GoVersion = val
}

// The response message for a sign-in request.
// Ref: #/components/schemas/SigninResponse
type SigninResponse struct {
	// The status of the response.
	Status OptSigninResponseStatus `json:"status"`
	// An optional message providing additional information about the response.
	Message OptString `json:"message"`
	// The response data for this request.
	Data OptSigninResponseData `json:"data"`
	// The operation time in microseconds.  This is the time it took to process
	//  the request and generate the response.
	OpTimeUs OptUint64 `json:"op_time_us"`
}

// GetStatus returns the value of Status.
func (s *SigninResponse) GetStatus() OptSigninResponseStatus {
	return s.Status
}

// GetMessage returns the value of Message.
func (s *SigninResponse) GetMessage() OptString {
	return s.Message
}

// GetData returns the value of Data.
func (s *SigninResponse) GetData() OptSigninResponseData {
	return s.Data
}

// GetOpTimeUs returns the value of OpTimeUs.
func (s *SigninResponse) GetOpTimeUs() OptUint64 {
	return s.OpTimeUs
}

// SetStatus sets the value of Status.
func (s *SigninResponse) SetStatus(val OptSigninResponseStatus) {
	s.Status = val
}

// SetMessage sets the value of Message.
func (s *SigninResponse) SetMessage(val OptString) {
	s.Message = val
}

// SetData sets the value of Data.
func (s *SigninResponse) SetData(val OptSigninResponseData) {
	s.Data = val
}

// SetOpTimeUs sets the value of OpTimeUs.
func (s *SigninResponse) SetOpTimeUs(val OptUint64) {
	s.OpTimeUs = val
}

// Ref: #/components/schemas/SigninResponseData
type SigninResponseData struct {
	//
	AuthorizationURL OptString `json:"authorization_url"`
}

// GetAuthorizationURL returns the value of AuthorizationURL.
func (s *SigninResponseData) GetAuthorizationURL() OptString {
	return s.AuthorizationURL
}

// SetAuthorizationURL sets the value of AuthorizationURL.
func (s *SigninResponseData) SetAuthorizationURL(val OptString) {
	s.AuthorizationURL = val
}

// The status of the response.
type SigninResponseStatus string

const (
	SigninResponseStatusSuccess SigninResponseStatus = "success"
	SigninResponseStatusError   SigninResponseStatus = "error"
)

// AllValues returns all SigninResponseStatus values.
func (SigninResponseStatus) AllValues() []SigninResponseStatus {
	return []SigninResponseStatus{
		SigninResponseStatusSuccess,
		SigninResponseStatusError,
	}
}

// MarshalText implements encoding.TextMarshaler.
func (s SigninResponseStatus) MarshalText() ([]byte, error) {
	switch s {
	case SigninResponseStatusSuccess:
		return []byte(s), nil
	case SigninResponseStatusError:
		return []byte(s), nil
	default:
		return nil, errors.Errorf("invalid value: %q", s)
	}
}

// UnmarshalText implements encoding.TextUnmarshaler.
func (s *SigninResponseStatus) UnmarshalText(data []byte) error {
	switch SigninResponseStatus(data) {
	case SigninResponseStatusSuccess:
		*s = SigninResponseStatusSuccess
		return nil
	case SigninResponseStatusError:
		*s = SigninResponseStatusError
		return nil
	default:
		return errors.Errorf("invalid value: %q", data)
	}
}

// The `Status` type defines a logical error model that is suitable for different programming environments, including REST APIs and RPC APIs. It is used by [gRPC](https://github.com/grpc). Each `Status` message contains three pieces of data: error code, error message, and error details. You can find out more about this error model and how to work with it in the [API Design Guide](https://cloud.google.com/apis/design/errors).
// Ref: #/components/schemas/Status
type Status struct {
	// The status code, which should be an enum value of [google.rpc.Code][google.rpc.Code].
	Code OptInt32 `json:"code"`
	// A developer-facing error message, which should be in English. Any user-facing error message should be localized and sent in the [google.rpc.Status.details][google.rpc.Status.details] field, or localized by the client.
	Message OptString `json:"message"`
	// A list of messages that carry the error details.  There is a common set of message types for APIs to use.
	Details []GoogleProtobufAny `json:"details"`
}

// GetCode returns the value of Code.
func (s *Status) GetCode() OptInt32 {
	return s.Code
}

// GetMessage returns the value of Message.
func (s *Status) GetMessage() OptString {
	return s.Message
}

// GetDetails returns the value of Details.
func (s *Status) GetDetails() []GoogleProtobufAny {
	return s.Details
}

// SetCode sets the value of Code.
func (s *Status) SetCode(val OptInt32) {
	s.Code = val
}

// SetMessage sets the value of Message.
func (s *Status) SetMessage(val OptString) {
	s.Message = val
}

// SetDetails sets the value of Details.
func (s *Status) SetDetails(val []GoogleProtobufAny) {
	s.Details = val
}

// StatusStatusCode wraps Status with StatusCode.
type StatusStatusCode struct {
	StatusCode int
	Response   Status
}

// GetStatusCode returns the value of StatusCode.
func (s *StatusStatusCode) GetStatusCode() int {
	return s.StatusCode
}

// GetResponse returns the value of Response.
func (s *StatusStatusCode) GetResponse() Status {
	return s.Response
}

// SetStatusCode sets the value of StatusCode.
func (s *StatusStatusCode) SetStatusCode(val int) {
	s.StatusCode = val
}

// SetResponse sets the value of Response.
func (s *StatusStatusCode) SetResponse(val Status) {
	s.Response = val
}
