// Code generated by ogen, DO NOT EDIT.

package platform

import (
	"context"
	"net/url"
	"strings"

	"github.com/go-faster/errors"

	"github.com/ogen-go/ogen/conv"
	ht "github.com/ogen-go/ogen/http"
	"github.com/ogen-go/ogen/ogenerrors"
	"github.com/ogen-go/ogen/uri"
)

func trimTrailingSlashes(u *url.URL) {
	u.Path = strings.TrimRight(u.Path, "/")
	u.RawPath = strings.TrimRight(u.RawPath, "/")
}

// Invoker invokes operations described by OpenAPI v3 specification.
type Invoker interface {
	// CreateCertificate invokes CreateCertificate operation.
	//
	// Upload a new certificate with the given configuration.
	//
	// POST /v1/certificates
	CreateCertificate(ctx context.Context, request *CreateCertificateRequest) (*CreateCertificateResponseStatusCode, error)
	// CreateInstance invokes CreateInstance operation.
	//
	// Creates one or more new instances.
	//
	// POST /v1/instances
	CreateInstance(ctx context.Context, request *CreateInstanceRequest) (*CreateInstanceResponseStatusCode, error)
	// CreateServiceGroup invokes CreateServiceGroup operation.
	//
	// Create a new service with the given configuration.
	//
	//  Note that the service properties like published ports can only be defined
	//  during creation.  They cannot be changed later.  Each port in a service can
	//  specify a list of handlers that determine how traffic arriving at the port
	//  is handled. See Connection Handlers for a complete overview.
	//
	// POST /v1/services
	CreateServiceGroup(ctx context.Context, request *CreateServiceGroupRequest) (*CreateServiceGroupResponseStatusCode, error)
	// DeleteCertificateByUUID invokes DeleteCertificateByUUID operation.
	//
	// Delete the specified certificate(s).  After this call the name of the
	//  certificate(s) are no longer valid.
	//
	// DELETE /v1/certificates/{uuid}
	DeleteCertificateByUUID(ctx context.Context, params DeleteCertificateByUUIDParams) (*DeleteCertificatesResponseStatusCode, error)
	// DeleteCertificates invokes DeleteCertificates operation.
	//
	// Delete a specified certificate by its UUID.  After this call the UUID of
	//  the certificate are no longer valid.
	//
	// DELETE /v1/certificates
	DeleteCertificates(ctx context.Context, request []DeleteCertificatesRequestID) (*DeleteCertificatesResponseStatusCode, error)
	// DeleteInstanceByUUID invokes DeleteInstanceByUUID operation.
	//
	// Delete a specified instance by its UUID.  After this call the UUID of the
	//  instances are no longer valid.  If the instances are currently running,
	//  they are force stopped.
	//
	// DELETE /v1/instances/{uuid}
	DeleteInstanceByUUID(ctx context.Context, params DeleteInstanceByUUIDParams) (*DeleteInstancesResponseStatusCode, error)
	// DeleteServiceGroupByUUID invokes DeleteServiceGroupByUUID operation.
	//
	// Delete the specified service group(s).  After this call the name of the
	//  service group(s) are no longer valid.
	//
	// DELETE /v1/services/{uuid}
	DeleteServiceGroupByUUID(ctx context.Context, params DeleteServiceGroupByUUIDParams) (*DeleteServiceGroupsResponseStatusCode, error)
	// DeleteServiceGroups invokes DeleteServiceGroups operation.
	//
	// Delete a specified service group by its UUID.  After this call the UUID of
	//  the service group are no longer valid.
	//
	// DELETE /v1/services
	DeleteServiceGroups(ctx context.Context, request []DeleteServiceGroupsRequestID) (*DeleteServiceGroupsResponseStatusCode, error)
	// GetCertificateByUUID invokes GetCertificateByUUID operation.
	//
	// Get a specified certificate by its UUID.
	//
	// GET /v1/certificates/{uuid}
	GetCertificateByUUID(ctx context.Context, params GetCertificateByUUIDParams) (*GetCertificatesResponseStatusCode, error)
	// GetCertificates invokes GetCertificates operation.
	//
	// Get one or many certificates with their current status and configuration.
	//  It's possible to filter this list by name or UUID.
	//
	// GET /v1/certificates
	GetCertificates(ctx context.Context, request []GetCertificatesRequestID, params GetCertificatesParams) (*GetCertificatesResponseStatusCode, error)
	// GetImageByDigest invokes GetImageByDigest operation.
	//
	// GetImageByDigest retrieves an image by its digest.
	//
	// GET /v1/images/digest/{digest}
	GetImageByDigest(ctx context.Context, params GetImageByDigestParams) (*GetImageResponseStatusCode, error)
	// GetImageByTag invokes GetImageByTag operation.
	//
	// GetImageByTag retrieves an image by its tag.
	//
	// GET /v1/images/tag/{tag}
	GetImageByTag(ctx context.Context, params GetImageByTagParams) (*GetImageResponseStatusCode, error)
	// GetInstanceByUUID invokes GetInstanceByUUID operation.
	//
	// Get a single instance by its ID which can either be its name or UUID.
	//
	// GET /v1/instances/{uuid}
	GetInstanceByUUID(ctx context.Context, params GetInstanceByUUIDParams) (*GetInstancesResponseStatusCode, error)
	// GetInstanceLogs invokes GetInstanceLogs operation.
	//
	// Retrieve the logs of an instance by its UUID or name.
	//
	// PUT /v1/instances/logs
	GetInstanceLogs(ctx context.Context, params GetInstanceLogsParams) (*GetInstanceLogsResponseStatusCode, error)
	// GetInstanceLogsByUUID invokes GetInstanceLogsByUUID operation.
	//
	// Retrieve the logs of an instance by its UUID.
	//
	// PUT /v1/instances/{uuid}/logs
	GetInstanceLogsByUUID(ctx context.Context, params GetInstanceLogsByUUIDParams) (*GetInstanceLogsResponseStatusCode, error)
	// GetInstanceMetrics invokes GetInstanceMetrics operation.
	//
	// Get the metrics of an instance by its UUID or name.
	//
	// PUT /v1/instances/metrics
	GetInstanceMetrics(ctx context.Context, params GetInstanceMetricsParams) (*GetInstanceMetricsResponseStatusCode, error)
	// GetInstanceMetricsByUUID invokes GetInstanceMetricsByUUID operation.
	//
	// Get the metrics of an instance by its UUID.
	//
	// PUT /v1/instances/{uuid}/metrics
	GetInstanceMetricsByUUID(ctx context.Context, params GetInstanceMetricsByUUIDParams) (*GetInstanceMetricsResponseStatusCode, error)
	// GetInstances invokes GetInstances operation.
	//
	// Get one or many instances with their current status and configuration.
	//  It's possible to filter this list by name or UUID.
	//
	// GET /v1/instances
	GetInstances(ctx context.Context, request []GetInstancesRequestID, params GetInstancesParams) (*GetInstancesResponseStatusCode, error)
	// GetServiceGroupByUUID invokes GetServiceGroupByUUID operation.
	//
	// Get a specified service group by its UUID.
	//
	// GET /v1/services/{uuid}
	GetServiceGroupByUUID(ctx context.Context, params GetServiceGroupByUUIDParams) (*GetServiceGroupsResponseStatusCode, error)
	// GetServiceGroups invokes GetServiceGroups operation.
	//
	// Get one or many service groups with their current status and configuration.
	//  It's possible to filter this list by name or UUID.
	//
	// GET /v1/services
	GetServiceGroups(ctx context.Context, request []GetServiceGroupsRequestID, params GetServiceGroupsParams) (*GetServiceGroupsResponseStatusCode, error)
	// StartInstanceByUUID invokes StartInstanceByUUID operation.
	//
	// Starts previously stopped instance by its UUID or does nothing if the
	//  instance is already running.
	//
	// PUT /v1/instances/{uuid}/start
	StartInstanceByUUID(ctx context.Context, params StartInstanceByUUIDParams) (*StartInstanceResponseStatusCode, error)
	// StopInstanceByUUID invokes StopInstanceByUUID operation.
	//
	// Stops a running instance by its UUID or does nothing if the instance is
	//  already stopped.
	//
	// PUT /v1/instances/{uuid}/stop
	StopInstanceByUUID(ctx context.Context, params StopInstanceByUUIDParams) (*StopInstanceResponseStatusCode, error)
	// StopInstances invokes StopInstances operation.
	//
	// Stops one or more running instance by their UUID(s) or name(s) or does
	//  nothing if the instance is already stopped.
	//
	// PUT /v1/instances/stop
	StopInstances(ctx context.Context, request []StopInstancesRequestID, params StopInstancesParams) (*StopInstanceResponseStatusCode, error)
	// WaitInstanceByUUID invokes WaitInstanceByUUID operation.
	//
	// Waits for an instance to reach a certain state by its UUID.
	//
	//  If the instance is already in the desired state, the request will return
	//  immediately.  If the instance is not in the desired state, the request will
	//  block until the instance reaches the desired state or the timeout is
	//  reached.  If the timeout is reached, the request will fail with an error.
	//  If the timeout is -1, the request will block indefinitely until the
	//  instance reaches the desired state.
	//
	// GET /v1/instances/{uuid}/wait
	WaitInstanceByUUID(ctx context.Context, params WaitInstanceByUUIDParams) (*WaitInstanceResponseStatusCode, error)
	// WaitInstances invokes WaitInstances operation.
	//
	// Waits for an instance to reach a certain state by its UUID or name.
	//
	//  If the instance is already in the desired state, the request will return
	//  immediately.  If the instance is not in the desired state, the request will
	//  block until the instance reaches the desired state or the timeout is
	//  reached.  If the timeout is reached, the request will fail with an error.
	//  If the timeout is -1, the request will block indefinitely until the
	//  instance reaches the desired state.
	//
	// GET /v1/instances/wait
	WaitInstances(ctx context.Context, request []WaitInstancesRequestID, params WaitInstancesParams) (*WaitInstanceResponseStatusCode, error)
}

// Client implements OAS client.
type Client struct {
	serverURL *url.URL
	sec       SecuritySource
	baseClient
}

// NewClient initializes new Client defined by OAS.
func NewClient(serverURL string, sec SecuritySource, opts ...ClientOption) (*Client, error) {
	u, err := url.Parse(serverURL)
	if err != nil {
		return nil, err
	}
	trimTrailingSlashes(u)

	c, err := newClientConfig(opts...).baseClient()
	if err != nil {
		return nil, err
	}
	return &Client{
		serverURL:  u,
		sec:        sec,
		baseClient: c,
	}, nil
}

type serverURLKey struct{}

// WithServerURL sets context key to override server URL.
func WithServerURL(ctx context.Context, u *url.URL) context.Context {
	return context.WithValue(ctx, serverURLKey{}, u)
}

func (c *Client) requestURL(ctx context.Context) *url.URL {
	u, ok := ctx.Value(serverURLKey{}).(*url.URL)
	if !ok {
		return c.serverURL
	}
	return u
}

// CreateCertificate invokes CreateCertificate operation.
//
// Upload a new certificate with the given configuration.
//
// POST /v1/certificates
func (c *Client) CreateCertificate(ctx context.Context, request *CreateCertificateRequest) (*CreateCertificateResponseStatusCode, error) {
	res, err := c.sendCreateCertificate(ctx, request)
	return res, err
}

func (c *Client) sendCreateCertificate(ctx context.Context, request *CreateCertificateRequest) (res *CreateCertificateResponseStatusCode, err error) {

	u := uri.Clone(c.requestURL(ctx))
	var pathParts [1]string
	pathParts[0] = "/v1/certificates"
	uri.AddPathParts(u, pathParts[:]...)

	r, err := ht.NewRequest(ctx, "POST", u)
	if err != nil {
		return res, errors.Wrap(err, "create request")
	}
	if err := encodeCreateCertificateRequest(request, r); err != nil {
		return res, errors.Wrap(err, "encode request")
	}

	{
		type bitset = [1]uint8
		var satisfied bitset
		{

			switch err := c.securityBearerToken(ctx, CreateCertificateOperation, r); {
			case err == nil: // if NO error
				satisfied[0] |= 1 << 0
			case errors.Is(err, ogenerrors.ErrSkipClientSecurity):
				// Skip this security.
			default:
				return res, errors.Wrap(err, "security \"BearerToken\"")
			}
		}

		if ok := func() bool {
		nextRequirement:
			for _, requirement := range []bitset{
				{0b00000001},
			} {
				for i, mask := range requirement {
					if satisfied[i]&mask != mask {
						continue nextRequirement
					}
				}
				return true
			}
			return false
		}(); !ok {
			return res, ogenerrors.ErrSecurityRequirementIsNotSatisfied
		}
	}

	resp, err := c.cfg.Client.Do(r)
	if err != nil {
		return res, errors.Wrap(err, "do request")
	}

	defer resp.Body.Close()

	result, err := decodeCreateCertificateResponse(resp)
	if err != nil {
		return res, errors.Wrap(err, "decode response")
	}

	return result, nil
}

// CreateInstance invokes CreateInstance operation.
//
// Creates one or more new instances.
//
// POST /v1/instances
func (c *Client) CreateInstance(ctx context.Context, request *CreateInstanceRequest) (*CreateInstanceResponseStatusCode, error) {
	res, err := c.sendCreateInstance(ctx, request)
	return res, err
}

func (c *Client) sendCreateInstance(ctx context.Context, request *CreateInstanceRequest) (res *CreateInstanceResponseStatusCode, err error) {

	u := uri.Clone(c.requestURL(ctx))
	var pathParts [1]string
	pathParts[0] = "/v1/instances"
	uri.AddPathParts(u, pathParts[:]...)

	r, err := ht.NewRequest(ctx, "POST", u)
	if err != nil {
		return res, errors.Wrap(err, "create request")
	}
	if err := encodeCreateInstanceRequest(request, r); err != nil {
		return res, errors.Wrap(err, "encode request")
	}

	{
		type bitset = [1]uint8
		var satisfied bitset
		{

			switch err := c.securityBearerToken(ctx, CreateInstanceOperation, r); {
			case err == nil: // if NO error
				satisfied[0] |= 1 << 0
			case errors.Is(err, ogenerrors.ErrSkipClientSecurity):
				// Skip this security.
			default:
				return res, errors.Wrap(err, "security \"BearerToken\"")
			}
		}

		if ok := func() bool {
		nextRequirement:
			for _, requirement := range []bitset{
				{0b00000001},
			} {
				for i, mask := range requirement {
					if satisfied[i]&mask != mask {
						continue nextRequirement
					}
				}
				return true
			}
			return false
		}(); !ok {
			return res, ogenerrors.ErrSecurityRequirementIsNotSatisfied
		}
	}

	resp, err := c.cfg.Client.Do(r)
	if err != nil {
		return res, errors.Wrap(err, "do request")
	}

	defer resp.Body.Close()

	result, err := decodeCreateInstanceResponse(resp)
	if err != nil {
		return res, errors.Wrap(err, "decode response")
	}

	return result, nil
}

// CreateServiceGroup invokes CreateServiceGroup operation.
//
// Create a new service with the given configuration.
//
//	Note that the service properties like published ports can only be defined
//	during creation.  They cannot be changed later.  Each port in a service can
//	specify a list of handlers that determine how traffic arriving at the port
//	is handled. See Connection Handlers for a complete overview.
//
// POST /v1/services
func (c *Client) CreateServiceGroup(ctx context.Context, request *CreateServiceGroupRequest) (*CreateServiceGroupResponseStatusCode, error) {
	res, err := c.sendCreateServiceGroup(ctx, request)
	return res, err
}

func (c *Client) sendCreateServiceGroup(ctx context.Context, request *CreateServiceGroupRequest) (res *CreateServiceGroupResponseStatusCode, err error) {

	u := uri.Clone(c.requestURL(ctx))
	var pathParts [1]string
	pathParts[0] = "/v1/services"
	uri.AddPathParts(u, pathParts[:]...)

	r, err := ht.NewRequest(ctx, "POST", u)
	if err != nil {
		return res, errors.Wrap(err, "create request")
	}
	if err := encodeCreateServiceGroupRequest(request, r); err != nil {
		return res, errors.Wrap(err, "encode request")
	}

	{
		type bitset = [1]uint8
		var satisfied bitset
		{

			switch err := c.securityBearerToken(ctx, CreateServiceGroupOperation, r); {
			case err == nil: // if NO error
				satisfied[0] |= 1 << 0
			case errors.Is(err, ogenerrors.ErrSkipClientSecurity):
				// Skip this security.
			default:
				return res, errors.Wrap(err, "security \"BearerToken\"")
			}
		}

		if ok := func() bool {
		nextRequirement:
			for _, requirement := range []bitset{
				{0b00000001},
			} {
				for i, mask := range requirement {
					if satisfied[i]&mask != mask {
						continue nextRequirement
					}
				}
				return true
			}
			return false
		}(); !ok {
			return res, ogenerrors.ErrSecurityRequirementIsNotSatisfied
		}
	}

	resp, err := c.cfg.Client.Do(r)
	if err != nil {
		return res, errors.Wrap(err, "do request")
	}

	defer resp.Body.Close()

	result, err := decodeCreateServiceGroupResponse(resp)
	if err != nil {
		return res, errors.Wrap(err, "decode response")
	}

	return result, nil
}

// DeleteCertificateByUUID invokes DeleteCertificateByUUID operation.
//
// Delete the specified certificate(s).  After this call the name of the
//
//	certificate(s) are no longer valid.
//
// DELETE /v1/certificates/{uuid}
func (c *Client) DeleteCertificateByUUID(ctx context.Context, params DeleteCertificateByUUIDParams) (*DeleteCertificatesResponseStatusCode, error) {
	res, err := c.sendDeleteCertificateByUUID(ctx, params)
	return res, err
}

func (c *Client) sendDeleteCertificateByUUID(ctx context.Context, params DeleteCertificateByUUIDParams) (res *DeleteCertificatesResponseStatusCode, err error) {

	u := uri.Clone(c.requestURL(ctx))
	var pathParts [2]string
	pathParts[0] = "/v1/certificates/"
	{
		// Encode "uuid" parameter.
		e := uri.NewPathEncoder(uri.PathEncoderConfig{
			Param:   "uuid",
			Style:   uri.PathStyleSimple,
			Explode: false,
		})
		if err := func() error {
			return e.EncodeValue(conv.StringToString(params.UUID))
		}(); err != nil {
			return res, errors.Wrap(err, "encode path")
		}
		encoded, err := e.Result()
		if err != nil {
			return res, errors.Wrap(err, "encode path")
		}
		pathParts[1] = encoded
	}
	uri.AddPathParts(u, pathParts[:]...)

	r, err := ht.NewRequest(ctx, "DELETE", u)
	if err != nil {
		return res, errors.Wrap(err, "create request")
	}

	{
		type bitset = [1]uint8
		var satisfied bitset
		{

			switch err := c.securityBearerToken(ctx, DeleteCertificateByUUIDOperation, r); {
			case err == nil: // if NO error
				satisfied[0] |= 1 << 0
			case errors.Is(err, ogenerrors.ErrSkipClientSecurity):
				// Skip this security.
			default:
				return res, errors.Wrap(err, "security \"BearerToken\"")
			}
		}

		if ok := func() bool {
		nextRequirement:
			for _, requirement := range []bitset{
				{0b00000001},
			} {
				for i, mask := range requirement {
					if satisfied[i]&mask != mask {
						continue nextRequirement
					}
				}
				return true
			}
			return false
		}(); !ok {
			return res, ogenerrors.ErrSecurityRequirementIsNotSatisfied
		}
	}

	resp, err := c.cfg.Client.Do(r)
	if err != nil {
		return res, errors.Wrap(err, "do request")
	}

	defer resp.Body.Close()

	result, err := decodeDeleteCertificateByUUIDResponse(resp)
	if err != nil {
		return res, errors.Wrap(err, "decode response")
	}

	return result, nil
}

// DeleteCertificates invokes DeleteCertificates operation.
//
// Delete a specified certificate by its UUID.  After this call the UUID of
//
//	the certificate are no longer valid.
//
// DELETE /v1/certificates
func (c *Client) DeleteCertificates(ctx context.Context, request []DeleteCertificatesRequestID) (*DeleteCertificatesResponseStatusCode, error) {
	res, err := c.sendDeleteCertificates(ctx, request)
	return res, err
}

func (c *Client) sendDeleteCertificates(ctx context.Context, request []DeleteCertificatesRequestID) (res *DeleteCertificatesResponseStatusCode, err error) {

	u := uri.Clone(c.requestURL(ctx))
	var pathParts [1]string
	pathParts[0] = "/v1/certificates"
	uri.AddPathParts(u, pathParts[:]...)

	r, err := ht.NewRequest(ctx, "DELETE", u)
	if err != nil {
		return res, errors.Wrap(err, "create request")
	}
	if err := encodeDeleteCertificatesRequest(request, r); err != nil {
		return res, errors.Wrap(err, "encode request")
	}

	{
		type bitset = [1]uint8
		var satisfied bitset
		{

			switch err := c.securityBearerToken(ctx, DeleteCertificatesOperation, r); {
			case err == nil: // if NO error
				satisfied[0] |= 1 << 0
			case errors.Is(err, ogenerrors.ErrSkipClientSecurity):
				// Skip this security.
			default:
				return res, errors.Wrap(err, "security \"BearerToken\"")
			}
		}

		if ok := func() bool {
		nextRequirement:
			for _, requirement := range []bitset{
				{0b00000001},
			} {
				for i, mask := range requirement {
					if satisfied[i]&mask != mask {
						continue nextRequirement
					}
				}
				return true
			}
			return false
		}(); !ok {
			return res, ogenerrors.ErrSecurityRequirementIsNotSatisfied
		}
	}

	resp, err := c.cfg.Client.Do(r)
	if err != nil {
		return res, errors.Wrap(err, "do request")
	}

	defer resp.Body.Close()

	result, err := decodeDeleteCertificatesResponse(resp)
	if err != nil {
		return res, errors.Wrap(err, "decode response")
	}

	return result, nil
}

// DeleteInstanceByUUID invokes DeleteInstanceByUUID operation.
//
// Delete a specified instance by its UUID.  After this call the UUID of the
//
//	instances are no longer valid.  If the instances are currently running,
//	they are force stopped.
//
// DELETE /v1/instances/{uuid}
func (c *Client) DeleteInstanceByUUID(ctx context.Context, params DeleteInstanceByUUIDParams) (*DeleteInstancesResponseStatusCode, error) {
	res, err := c.sendDeleteInstanceByUUID(ctx, params)
	return res, err
}

func (c *Client) sendDeleteInstanceByUUID(ctx context.Context, params DeleteInstanceByUUIDParams) (res *DeleteInstancesResponseStatusCode, err error) {

	u := uri.Clone(c.requestURL(ctx))
	var pathParts [2]string
	pathParts[0] = "/v1/instances/"
	{
		// Encode "uuid" parameter.
		e := uri.NewPathEncoder(uri.PathEncoderConfig{
			Param:   "uuid",
			Style:   uri.PathStyleSimple,
			Explode: false,
		})
		if err := func() error {
			return e.EncodeValue(conv.StringToString(params.UUID))
		}(); err != nil {
			return res, errors.Wrap(err, "encode path")
		}
		encoded, err := e.Result()
		if err != nil {
			return res, errors.Wrap(err, "encode path")
		}
		pathParts[1] = encoded
	}
	uri.AddPathParts(u, pathParts[:]...)

	r, err := ht.NewRequest(ctx, "DELETE", u)
	if err != nil {
		return res, errors.Wrap(err, "create request")
	}

	{
		type bitset = [1]uint8
		var satisfied bitset
		{

			switch err := c.securityBearerToken(ctx, DeleteInstanceByUUIDOperation, r); {
			case err == nil: // if NO error
				satisfied[0] |= 1 << 0
			case errors.Is(err, ogenerrors.ErrSkipClientSecurity):
				// Skip this security.
			default:
				return res, errors.Wrap(err, "security \"BearerToken\"")
			}
		}

		if ok := func() bool {
		nextRequirement:
			for _, requirement := range []bitset{
				{0b00000001},
			} {
				for i, mask := range requirement {
					if satisfied[i]&mask != mask {
						continue nextRequirement
					}
				}
				return true
			}
			return false
		}(); !ok {
			return res, ogenerrors.ErrSecurityRequirementIsNotSatisfied
		}
	}

	resp, err := c.cfg.Client.Do(r)
	if err != nil {
		return res, errors.Wrap(err, "do request")
	}

	defer resp.Body.Close()

	result, err := decodeDeleteInstanceByUUIDResponse(resp)
	if err != nil {
		return res, errors.Wrap(err, "decode response")
	}

	return result, nil
}

// DeleteServiceGroupByUUID invokes DeleteServiceGroupByUUID operation.
//
// Delete the specified service group(s).  After this call the name of the
//
//	service group(s) are no longer valid.
//
// DELETE /v1/services/{uuid}
func (c *Client) DeleteServiceGroupByUUID(ctx context.Context, params DeleteServiceGroupByUUIDParams) (*DeleteServiceGroupsResponseStatusCode, error) {
	res, err := c.sendDeleteServiceGroupByUUID(ctx, params)
	return res, err
}

func (c *Client) sendDeleteServiceGroupByUUID(ctx context.Context, params DeleteServiceGroupByUUIDParams) (res *DeleteServiceGroupsResponseStatusCode, err error) {

	u := uri.Clone(c.requestURL(ctx))
	var pathParts [2]string
	pathParts[0] = "/v1/services/"
	{
		// Encode "uuid" parameter.
		e := uri.NewPathEncoder(uri.PathEncoderConfig{
			Param:   "uuid",
			Style:   uri.PathStyleSimple,
			Explode: false,
		})
		if err := func() error {
			return e.EncodeValue(conv.StringToString(params.UUID))
		}(); err != nil {
			return res, errors.Wrap(err, "encode path")
		}
		encoded, err := e.Result()
		if err != nil {
			return res, errors.Wrap(err, "encode path")
		}
		pathParts[1] = encoded
	}
	uri.AddPathParts(u, pathParts[:]...)

	r, err := ht.NewRequest(ctx, "DELETE", u)
	if err != nil {
		return res, errors.Wrap(err, "create request")
	}

	{
		type bitset = [1]uint8
		var satisfied bitset
		{

			switch err := c.securityBearerToken(ctx, DeleteServiceGroupByUUIDOperation, r); {
			case err == nil: // if NO error
				satisfied[0] |= 1 << 0
			case errors.Is(err, ogenerrors.ErrSkipClientSecurity):
				// Skip this security.
			default:
				return res, errors.Wrap(err, "security \"BearerToken\"")
			}
		}

		if ok := func() bool {
		nextRequirement:
			for _, requirement := range []bitset{
				{0b00000001},
			} {
				for i, mask := range requirement {
					if satisfied[i]&mask != mask {
						continue nextRequirement
					}
				}
				return true
			}
			return false
		}(); !ok {
			return res, ogenerrors.ErrSecurityRequirementIsNotSatisfied
		}
	}

	resp, err := c.cfg.Client.Do(r)
	if err != nil {
		return res, errors.Wrap(err, "do request")
	}

	defer resp.Body.Close()

	result, err := decodeDeleteServiceGroupByUUIDResponse(resp)
	if err != nil {
		return res, errors.Wrap(err, "decode response")
	}

	return result, nil
}

// DeleteServiceGroups invokes DeleteServiceGroups operation.
//
// Delete a specified service group by its UUID.  After this call the UUID of
//
//	the service group are no longer valid.
//
// DELETE /v1/services
func (c *Client) DeleteServiceGroups(ctx context.Context, request []DeleteServiceGroupsRequestID) (*DeleteServiceGroupsResponseStatusCode, error) {
	res, err := c.sendDeleteServiceGroups(ctx, request)
	return res, err
}

func (c *Client) sendDeleteServiceGroups(ctx context.Context, request []DeleteServiceGroupsRequestID) (res *DeleteServiceGroupsResponseStatusCode, err error) {

	u := uri.Clone(c.requestURL(ctx))
	var pathParts [1]string
	pathParts[0] = "/v1/services"
	uri.AddPathParts(u, pathParts[:]...)

	r, err := ht.NewRequest(ctx, "DELETE", u)
	if err != nil {
		return res, errors.Wrap(err, "create request")
	}
	if err := encodeDeleteServiceGroupsRequest(request, r); err != nil {
		return res, errors.Wrap(err, "encode request")
	}

	{
		type bitset = [1]uint8
		var satisfied bitset
		{

			switch err := c.securityBearerToken(ctx, DeleteServiceGroupsOperation, r); {
			case err == nil: // if NO error
				satisfied[0] |= 1 << 0
			case errors.Is(err, ogenerrors.ErrSkipClientSecurity):
				// Skip this security.
			default:
				return res, errors.Wrap(err, "security \"BearerToken\"")
			}
		}

		if ok := func() bool {
		nextRequirement:
			for _, requirement := range []bitset{
				{0b00000001},
			} {
				for i, mask := range requirement {
					if satisfied[i]&mask != mask {
						continue nextRequirement
					}
				}
				return true
			}
			return false
		}(); !ok {
			return res, ogenerrors.ErrSecurityRequirementIsNotSatisfied
		}
	}

	resp, err := c.cfg.Client.Do(r)
	if err != nil {
		return res, errors.Wrap(err, "do request")
	}

	defer resp.Body.Close()

	result, err := decodeDeleteServiceGroupsResponse(resp)
	if err != nil {
		return res, errors.Wrap(err, "decode response")
	}

	return result, nil
}

// GetCertificateByUUID invokes GetCertificateByUUID operation.
//
// Get a specified certificate by its UUID.
//
// GET /v1/certificates/{uuid}
func (c *Client) GetCertificateByUUID(ctx context.Context, params GetCertificateByUUIDParams) (*GetCertificatesResponseStatusCode, error) {
	res, err := c.sendGetCertificateByUUID(ctx, params)
	return res, err
}

func (c *Client) sendGetCertificateByUUID(ctx context.Context, params GetCertificateByUUIDParams) (res *GetCertificatesResponseStatusCode, err error) {

	u := uri.Clone(c.requestURL(ctx))
	var pathParts [2]string
	pathParts[0] = "/v1/certificates/"
	{
		// Encode "uuid" parameter.
		e := uri.NewPathEncoder(uri.PathEncoderConfig{
			Param:   "uuid",
			Style:   uri.PathStyleSimple,
			Explode: false,
		})
		if err := func() error {
			return e.EncodeValue(conv.StringToString(params.UUID))
		}(); err != nil {
			return res, errors.Wrap(err, "encode path")
		}
		encoded, err := e.Result()
		if err != nil {
			return res, errors.Wrap(err, "encode path")
		}
		pathParts[1] = encoded
	}
	uri.AddPathParts(u, pathParts[:]...)

	r, err := ht.NewRequest(ctx, "GET", u)
	if err != nil {
		return res, errors.Wrap(err, "create request")
	}

	{
		type bitset = [1]uint8
		var satisfied bitset
		{

			switch err := c.securityBearerToken(ctx, GetCertificateByUUIDOperation, r); {
			case err == nil: // if NO error
				satisfied[0] |= 1 << 0
			case errors.Is(err, ogenerrors.ErrSkipClientSecurity):
				// Skip this security.
			default:
				return res, errors.Wrap(err, "security \"BearerToken\"")
			}
		}

		if ok := func() bool {
		nextRequirement:
			for _, requirement := range []bitset{
				{0b00000001},
			} {
				for i, mask := range requirement {
					if satisfied[i]&mask != mask {
						continue nextRequirement
					}
				}
				return true
			}
			return false
		}(); !ok {
			return res, ogenerrors.ErrSecurityRequirementIsNotSatisfied
		}
	}

	resp, err := c.cfg.Client.Do(r)
	if err != nil {
		return res, errors.Wrap(err, "do request")
	}

	defer resp.Body.Close()

	result, err := decodeGetCertificateByUUIDResponse(resp)
	if err != nil {
		return res, errors.Wrap(err, "decode response")
	}

	return result, nil
}

// GetCertificates invokes GetCertificates operation.
//
// Get one or many certificates with their current status and configuration.
//
//	It's possible to filter this list by name or UUID.
//
// GET /v1/certificates
func (c *Client) GetCertificates(ctx context.Context, request []GetCertificatesRequestID, params GetCertificatesParams) (*GetCertificatesResponseStatusCode, error) {
	res, err := c.sendGetCertificates(ctx, request, params)
	return res, err
}

func (c *Client) sendGetCertificates(ctx context.Context, request []GetCertificatesRequestID, params GetCertificatesParams) (res *GetCertificatesResponseStatusCode, err error) {

	u := uri.Clone(c.requestURL(ctx))
	var pathParts [1]string
	pathParts[0] = "/v1/certificates"
	uri.AddPathParts(u, pathParts[:]...)

	q := uri.NewQueryEncoder()
	{
		// Encode "details" parameter.
		cfg := uri.QueryParameterEncodingConfig{
			Name:    "details",
			Style:   uri.QueryStyleForm,
			Explode: true,
		}

		if err := q.EncodeParam(cfg, func(e uri.Encoder) error {
			if val, ok := params.Details.Get(); ok {
				return e.EncodeValue(conv.BoolToString(val))
			}
			return nil
		}); err != nil {
			return res, errors.Wrap(err, "encode query")
		}
	}
	u.RawQuery = q.Values().Encode()

	r, err := ht.NewRequest(ctx, "GET", u)
	if err != nil {
		return res, errors.Wrap(err, "create request")
	}
	if err := encodeGetCertificatesRequest(request, r); err != nil {
		return res, errors.Wrap(err, "encode request")
	}

	{
		type bitset = [1]uint8
		var satisfied bitset
		{

			switch err := c.securityBearerToken(ctx, GetCertificatesOperation, r); {
			case err == nil: // if NO error
				satisfied[0] |= 1 << 0
			case errors.Is(err, ogenerrors.ErrSkipClientSecurity):
				// Skip this security.
			default:
				return res, errors.Wrap(err, "security \"BearerToken\"")
			}
		}

		if ok := func() bool {
		nextRequirement:
			for _, requirement := range []bitset{
				{0b00000001},
			} {
				for i, mask := range requirement {
					if satisfied[i]&mask != mask {
						continue nextRequirement
					}
				}
				return true
			}
			return false
		}(); !ok {
			return res, ogenerrors.ErrSecurityRequirementIsNotSatisfied
		}
	}

	resp, err := c.cfg.Client.Do(r)
	if err != nil {
		return res, errors.Wrap(err, "do request")
	}

	defer resp.Body.Close()

	result, err := decodeGetCertificatesResponse(resp)
	if err != nil {
		return res, errors.Wrap(err, "decode response")
	}

	return result, nil
}

// GetImageByDigest invokes GetImageByDigest operation.
//
// GetImageByDigest retrieves an image by its digest.
//
// GET /v1/images/digest/{digest}
func (c *Client) GetImageByDigest(ctx context.Context, params GetImageByDigestParams) (*GetImageResponseStatusCode, error) {
	res, err := c.sendGetImageByDigest(ctx, params)
	return res, err
}

func (c *Client) sendGetImageByDigest(ctx context.Context, params GetImageByDigestParams) (res *GetImageResponseStatusCode, err error) {

	u := uri.Clone(c.requestURL(ctx))
	var pathParts [2]string
	pathParts[0] = "/v1/images/digest/"
	{
		// Encode "digest" parameter.
		e := uri.NewPathEncoder(uri.PathEncoderConfig{
			Param:   "digest",
			Style:   uri.PathStyleSimple,
			Explode: false,
		})
		if err := func() error {
			return e.EncodeValue(conv.StringToString(params.Digest))
		}(); err != nil {
			return res, errors.Wrap(err, "encode path")
		}
		encoded, err := e.Result()
		if err != nil {
			return res, errors.Wrap(err, "encode path")
		}
		pathParts[1] = encoded
	}
	uri.AddPathParts(u, pathParts[:]...)

	r, err := ht.NewRequest(ctx, "GET", u)
	if err != nil {
		return res, errors.Wrap(err, "create request")
	}

	{
		type bitset = [1]uint8
		var satisfied bitset
		{

			switch err := c.securityBearerToken(ctx, GetImageByDigestOperation, r); {
			case err == nil: // if NO error
				satisfied[0] |= 1 << 0
			case errors.Is(err, ogenerrors.ErrSkipClientSecurity):
				// Skip this security.
			default:
				return res, errors.Wrap(err, "security \"BearerToken\"")
			}
		}

		if ok := func() bool {
		nextRequirement:
			for _, requirement := range []bitset{
				{0b00000001},
			} {
				for i, mask := range requirement {
					if satisfied[i]&mask != mask {
						continue nextRequirement
					}
				}
				return true
			}
			return false
		}(); !ok {
			return res, ogenerrors.ErrSecurityRequirementIsNotSatisfied
		}
	}

	resp, err := c.cfg.Client.Do(r)
	if err != nil {
		return res, errors.Wrap(err, "do request")
	}

	defer resp.Body.Close()

	result, err := decodeGetImageByDigestResponse(resp)
	if err != nil {
		return res, errors.Wrap(err, "decode response")
	}

	return result, nil
}

// GetImageByTag invokes GetImageByTag operation.
//
// GetImageByTag retrieves an image by its tag.
//
// GET /v1/images/tag/{tag}
func (c *Client) GetImageByTag(ctx context.Context, params GetImageByTagParams) (*GetImageResponseStatusCode, error) {
	res, err := c.sendGetImageByTag(ctx, params)
	return res, err
}

func (c *Client) sendGetImageByTag(ctx context.Context, params GetImageByTagParams) (res *GetImageResponseStatusCode, err error) {

	u := uri.Clone(c.requestURL(ctx))
	var pathParts [2]string
	pathParts[0] = "/v1/images/tag/"
	{
		// Encode "tag" parameter.
		e := uri.NewPathEncoder(uri.PathEncoderConfig{
			Param:   "tag",
			Style:   uri.PathStyleSimple,
			Explode: false,
		})
		if err := func() error {
			return e.EncodeValue(conv.StringToString(params.Tag))
		}(); err != nil {
			return res, errors.Wrap(err, "encode path")
		}
		encoded, err := e.Result()
		if err != nil {
			return res, errors.Wrap(err, "encode path")
		}
		pathParts[1] = encoded
	}
	uri.AddPathParts(u, pathParts[:]...)

	r, err := ht.NewRequest(ctx, "GET", u)
	if err != nil {
		return res, errors.Wrap(err, "create request")
	}

	{
		type bitset = [1]uint8
		var satisfied bitset
		{

			switch err := c.securityBearerToken(ctx, GetImageByTagOperation, r); {
			case err == nil: // if NO error
				satisfied[0] |= 1 << 0
			case errors.Is(err, ogenerrors.ErrSkipClientSecurity):
				// Skip this security.
			default:
				return res, errors.Wrap(err, "security \"BearerToken\"")
			}
		}

		if ok := func() bool {
		nextRequirement:
			for _, requirement := range []bitset{
				{0b00000001},
			} {
				for i, mask := range requirement {
					if satisfied[i]&mask != mask {
						continue nextRequirement
					}
				}
				return true
			}
			return false
		}(); !ok {
			return res, ogenerrors.ErrSecurityRequirementIsNotSatisfied
		}
	}

	resp, err := c.cfg.Client.Do(r)
	if err != nil {
		return res, errors.Wrap(err, "do request")
	}

	defer resp.Body.Close()

	result, err := decodeGetImageByTagResponse(resp)
	if err != nil {
		return res, errors.Wrap(err, "decode response")
	}

	return result, nil
}

// GetInstanceByUUID invokes GetInstanceByUUID operation.
//
// Get a single instance by its ID which can either be its name or UUID.
//
// GET /v1/instances/{uuid}
func (c *Client) GetInstanceByUUID(ctx context.Context, params GetInstanceByUUIDParams) (*GetInstancesResponseStatusCode, error) {
	res, err := c.sendGetInstanceByUUID(ctx, params)
	return res, err
}

func (c *Client) sendGetInstanceByUUID(ctx context.Context, params GetInstanceByUUIDParams) (res *GetInstancesResponseStatusCode, err error) {

	u := uri.Clone(c.requestURL(ctx))
	var pathParts [2]string
	pathParts[0] = "/v1/instances/"
	{
		// Encode "uuid" parameter.
		e := uri.NewPathEncoder(uri.PathEncoderConfig{
			Param:   "uuid",
			Style:   uri.PathStyleSimple,
			Explode: false,
		})
		if err := func() error {
			return e.EncodeValue(conv.StringToString(params.UUID))
		}(); err != nil {
			return res, errors.Wrap(err, "encode path")
		}
		encoded, err := e.Result()
		if err != nil {
			return res, errors.Wrap(err, "encode path")
		}
		pathParts[1] = encoded
	}
	uri.AddPathParts(u, pathParts[:]...)

	r, err := ht.NewRequest(ctx, "GET", u)
	if err != nil {
		return res, errors.Wrap(err, "create request")
	}

	{
		type bitset = [1]uint8
		var satisfied bitset
		{

			switch err := c.securityBearerToken(ctx, GetInstanceByUUIDOperation, r); {
			case err == nil: // if NO error
				satisfied[0] |= 1 << 0
			case errors.Is(err, ogenerrors.ErrSkipClientSecurity):
				// Skip this security.
			default:
				return res, errors.Wrap(err, "security \"BearerToken\"")
			}
		}

		if ok := func() bool {
		nextRequirement:
			for _, requirement := range []bitset{
				{0b00000001},
			} {
				for i, mask := range requirement {
					if satisfied[i]&mask != mask {
						continue nextRequirement
					}
				}
				return true
			}
			return false
		}(); !ok {
			return res, ogenerrors.ErrSecurityRequirementIsNotSatisfied
		}
	}

	resp, err := c.cfg.Client.Do(r)
	if err != nil {
		return res, errors.Wrap(err, "do request")
	}

	defer resp.Body.Close()

	result, err := decodeGetInstanceByUUIDResponse(resp)
	if err != nil {
		return res, errors.Wrap(err, "decode response")
	}

	return result, nil
}

// GetInstanceLogs invokes GetInstanceLogs operation.
//
// Retrieve the logs of an instance by its UUID or name.
//
// PUT /v1/instances/logs
func (c *Client) GetInstanceLogs(ctx context.Context, params GetInstanceLogsParams) (*GetInstanceLogsResponseStatusCode, error) {
	res, err := c.sendGetInstanceLogs(ctx, params)
	return res, err
}

func (c *Client) sendGetInstanceLogs(ctx context.Context, params GetInstanceLogsParams) (res *GetInstanceLogsResponseStatusCode, err error) {

	u := uri.Clone(c.requestURL(ctx))
	var pathParts [1]string
	pathParts[0] = "/v1/instances/logs"
	uri.AddPathParts(u, pathParts[:]...)

	q := uri.NewQueryEncoder()
	{
		// Encode "uuid" parameter.
		cfg := uri.QueryParameterEncodingConfig{
			Name:    "uuid",
			Style:   uri.QueryStyleForm,
			Explode: true,
		}

		if err := q.EncodeParam(cfg, func(e uri.Encoder) error {
			if val, ok := params.UUID.Get(); ok {
				return e.EncodeValue(conv.StringToString(val))
			}
			return nil
		}); err != nil {
			return res, errors.Wrap(err, "encode query")
		}
	}
	{
		// Encode "name" parameter.
		cfg := uri.QueryParameterEncodingConfig{
			Name:    "name",
			Style:   uri.QueryStyleForm,
			Explode: true,
		}

		if err := q.EncodeParam(cfg, func(e uri.Encoder) error {
			if val, ok := params.Name.Get(); ok {
				return e.EncodeValue(conv.StringToString(val))
			}
			return nil
		}); err != nil {
			return res, errors.Wrap(err, "encode query")
		}
	}
	{
		// Encode "offset" parameter.
		cfg := uri.QueryParameterEncodingConfig{
			Name:    "offset",
			Style:   uri.QueryStyleForm,
			Explode: true,
		}

		if err := q.EncodeParam(cfg, func(e uri.Encoder) error {
			if val, ok := params.Offset.Get(); ok {
				return e.EncodeValue(conv.Uint64ToString(val))
			}
			return nil
		}); err != nil {
			return res, errors.Wrap(err, "encode query")
		}
	}
	{
		// Encode "limit" parameter.
		cfg := uri.QueryParameterEncodingConfig{
			Name:    "limit",
			Style:   uri.QueryStyleForm,
			Explode: true,
		}

		if err := q.EncodeParam(cfg, func(e uri.Encoder) error {
			if val, ok := params.Limit.Get(); ok {
				return e.EncodeValue(conv.Int64ToString(val))
			}
			return nil
		}); err != nil {
			return res, errors.Wrap(err, "encode query")
		}
	}
	u.RawQuery = q.Values().Encode()

	r, err := ht.NewRequest(ctx, "PUT", u)
	if err != nil {
		return res, errors.Wrap(err, "create request")
	}

	{
		type bitset = [1]uint8
		var satisfied bitset
		{

			switch err := c.securityBearerToken(ctx, GetInstanceLogsOperation, r); {
			case err == nil: // if NO error
				satisfied[0] |= 1 << 0
			case errors.Is(err, ogenerrors.ErrSkipClientSecurity):
				// Skip this security.
			default:
				return res, errors.Wrap(err, "security \"BearerToken\"")
			}
		}

		if ok := func() bool {
		nextRequirement:
			for _, requirement := range []bitset{
				{0b00000001},
			} {
				for i, mask := range requirement {
					if satisfied[i]&mask != mask {
						continue nextRequirement
					}
				}
				return true
			}
			return false
		}(); !ok {
			return res, ogenerrors.ErrSecurityRequirementIsNotSatisfied
		}
	}

	resp, err := c.cfg.Client.Do(r)
	if err != nil {
		return res, errors.Wrap(err, "do request")
	}

	defer resp.Body.Close()

	result, err := decodeGetInstanceLogsResponse(resp)
	if err != nil {
		return res, errors.Wrap(err, "decode response")
	}

	return result, nil
}

// GetInstanceLogsByUUID invokes GetInstanceLogsByUUID operation.
//
// Retrieve the logs of an instance by its UUID.
//
// PUT /v1/instances/{uuid}/logs
func (c *Client) GetInstanceLogsByUUID(ctx context.Context, params GetInstanceLogsByUUIDParams) (*GetInstanceLogsResponseStatusCode, error) {
	res, err := c.sendGetInstanceLogsByUUID(ctx, params)
	return res, err
}

func (c *Client) sendGetInstanceLogsByUUID(ctx context.Context, params GetInstanceLogsByUUIDParams) (res *GetInstanceLogsResponseStatusCode, err error) {

	u := uri.Clone(c.requestURL(ctx))
	var pathParts [3]string
	pathParts[0] = "/v1/instances/"
	{
		// Encode "uuid" parameter.
		e := uri.NewPathEncoder(uri.PathEncoderConfig{
			Param:   "uuid",
			Style:   uri.PathStyleSimple,
			Explode: false,
		})
		if err := func() error {
			return e.EncodeValue(conv.StringToString(params.UUID))
		}(); err != nil {
			return res, errors.Wrap(err, "encode path")
		}
		encoded, err := e.Result()
		if err != nil {
			return res, errors.Wrap(err, "encode path")
		}
		pathParts[1] = encoded
	}
	pathParts[2] = "/logs"
	uri.AddPathParts(u, pathParts[:]...)

	q := uri.NewQueryEncoder()
	{
		// Encode "offset" parameter.
		cfg := uri.QueryParameterEncodingConfig{
			Name:    "offset",
			Style:   uri.QueryStyleForm,
			Explode: true,
		}

		if err := q.EncodeParam(cfg, func(e uri.Encoder) error {
			if val, ok := params.Offset.Get(); ok {
				return e.EncodeValue(conv.Uint64ToString(val))
			}
			return nil
		}); err != nil {
			return res, errors.Wrap(err, "encode query")
		}
	}
	{
		// Encode "limit" parameter.
		cfg := uri.QueryParameterEncodingConfig{
			Name:    "limit",
			Style:   uri.QueryStyleForm,
			Explode: true,
		}

		if err := q.EncodeParam(cfg, func(e uri.Encoder) error {
			if val, ok := params.Limit.Get(); ok {
				return e.EncodeValue(conv.Int64ToString(val))
			}
			return nil
		}); err != nil {
			return res, errors.Wrap(err, "encode query")
		}
	}
	u.RawQuery = q.Values().Encode()

	r, err := ht.NewRequest(ctx, "PUT", u)
	if err != nil {
		return res, errors.Wrap(err, "create request")
	}

	{
		type bitset = [1]uint8
		var satisfied bitset
		{

			switch err := c.securityBearerToken(ctx, GetInstanceLogsByUUIDOperation, r); {
			case err == nil: // if NO error
				satisfied[0] |= 1 << 0
			case errors.Is(err, ogenerrors.ErrSkipClientSecurity):
				// Skip this security.
			default:
				return res, errors.Wrap(err, "security \"BearerToken\"")
			}
		}

		if ok := func() bool {
		nextRequirement:
			for _, requirement := range []bitset{
				{0b00000001},
			} {
				for i, mask := range requirement {
					if satisfied[i]&mask != mask {
						continue nextRequirement
					}
				}
				return true
			}
			return false
		}(); !ok {
			return res, ogenerrors.ErrSecurityRequirementIsNotSatisfied
		}
	}

	resp, err := c.cfg.Client.Do(r)
	if err != nil {
		return res, errors.Wrap(err, "do request")
	}

	defer resp.Body.Close()

	result, err := decodeGetInstanceLogsByUUIDResponse(resp)
	if err != nil {
		return res, errors.Wrap(err, "decode response")
	}

	return result, nil
}

// GetInstanceMetrics invokes GetInstanceMetrics operation.
//
// Get the metrics of an instance by its UUID or name.
//
// PUT /v1/instances/metrics
func (c *Client) GetInstanceMetrics(ctx context.Context, params GetInstanceMetricsParams) (*GetInstanceMetricsResponseStatusCode, error) {
	res, err := c.sendGetInstanceMetrics(ctx, params)
	return res, err
}

func (c *Client) sendGetInstanceMetrics(ctx context.Context, params GetInstanceMetricsParams) (res *GetInstanceMetricsResponseStatusCode, err error) {

	u := uri.Clone(c.requestURL(ctx))
	var pathParts [1]string
	pathParts[0] = "/v1/instances/metrics"
	uri.AddPathParts(u, pathParts[:]...)

	q := uri.NewQueryEncoder()
	{
		// Encode "uuid" parameter.
		cfg := uri.QueryParameterEncodingConfig{
			Name:    "uuid",
			Style:   uri.QueryStyleForm,
			Explode: true,
		}

		if err := q.EncodeParam(cfg, func(e uri.Encoder) error {
			if val, ok := params.UUID.Get(); ok {
				return e.EncodeValue(conv.StringToString(val))
			}
			return nil
		}); err != nil {
			return res, errors.Wrap(err, "encode query")
		}
	}
	{
		// Encode "name" parameter.
		cfg := uri.QueryParameterEncodingConfig{
			Name:    "name",
			Style:   uri.QueryStyleForm,
			Explode: true,
		}

		if err := q.EncodeParam(cfg, func(e uri.Encoder) error {
			if val, ok := params.Name.Get(); ok {
				return e.EncodeValue(conv.StringToString(val))
			}
			return nil
		}); err != nil {
			return res, errors.Wrap(err, "encode query")
		}
	}
	u.RawQuery = q.Values().Encode()

	r, err := ht.NewRequest(ctx, "PUT", u)
	if err != nil {
		return res, errors.Wrap(err, "create request")
	}

	{
		type bitset = [1]uint8
		var satisfied bitset
		{

			switch err := c.securityBearerToken(ctx, GetInstanceMetricsOperation, r); {
			case err == nil: // if NO error
				satisfied[0] |= 1 << 0
			case errors.Is(err, ogenerrors.ErrSkipClientSecurity):
				// Skip this security.
			default:
				return res, errors.Wrap(err, "security \"BearerToken\"")
			}
		}

		if ok := func() bool {
		nextRequirement:
			for _, requirement := range []bitset{
				{0b00000001},
			} {
				for i, mask := range requirement {
					if satisfied[i]&mask != mask {
						continue nextRequirement
					}
				}
				return true
			}
			return false
		}(); !ok {
			return res, ogenerrors.ErrSecurityRequirementIsNotSatisfied
		}
	}

	resp, err := c.cfg.Client.Do(r)
	if err != nil {
		return res, errors.Wrap(err, "do request")
	}

	defer resp.Body.Close()

	result, err := decodeGetInstanceMetricsResponse(resp)
	if err != nil {
		return res, errors.Wrap(err, "decode response")
	}

	return result, nil
}

// GetInstanceMetricsByUUID invokes GetInstanceMetricsByUUID operation.
//
// Get the metrics of an instance by its UUID.
//
// PUT /v1/instances/{uuid}/metrics
func (c *Client) GetInstanceMetricsByUUID(ctx context.Context, params GetInstanceMetricsByUUIDParams) (*GetInstanceMetricsResponseStatusCode, error) {
	res, err := c.sendGetInstanceMetricsByUUID(ctx, params)
	return res, err
}

func (c *Client) sendGetInstanceMetricsByUUID(ctx context.Context, params GetInstanceMetricsByUUIDParams) (res *GetInstanceMetricsResponseStatusCode, err error) {

	u := uri.Clone(c.requestURL(ctx))
	var pathParts [3]string
	pathParts[0] = "/v1/instances/"
	{
		// Encode "uuid" parameter.
		e := uri.NewPathEncoder(uri.PathEncoderConfig{
			Param:   "uuid",
			Style:   uri.PathStyleSimple,
			Explode: false,
		})
		if err := func() error {
			return e.EncodeValue(conv.StringToString(params.UUID))
		}(); err != nil {
			return res, errors.Wrap(err, "encode path")
		}
		encoded, err := e.Result()
		if err != nil {
			return res, errors.Wrap(err, "encode path")
		}
		pathParts[1] = encoded
	}
	pathParts[2] = "/metrics"
	uri.AddPathParts(u, pathParts[:]...)

	r, err := ht.NewRequest(ctx, "PUT", u)
	if err != nil {
		return res, errors.Wrap(err, "create request")
	}

	{
		type bitset = [1]uint8
		var satisfied bitset
		{

			switch err := c.securityBearerToken(ctx, GetInstanceMetricsByUUIDOperation, r); {
			case err == nil: // if NO error
				satisfied[0] |= 1 << 0
			case errors.Is(err, ogenerrors.ErrSkipClientSecurity):
				// Skip this security.
			default:
				return res, errors.Wrap(err, "security \"BearerToken\"")
			}
		}

		if ok := func() bool {
		nextRequirement:
			for _, requirement := range []bitset{
				{0b00000001},
			} {
				for i, mask := range requirement {
					if satisfied[i]&mask != mask {
						continue nextRequirement
					}
				}
				return true
			}
			return false
		}(); !ok {
			return res, ogenerrors.ErrSecurityRequirementIsNotSatisfied
		}
	}

	resp, err := c.cfg.Client.Do(r)
	if err != nil {
		return res, errors.Wrap(err, "do request")
	}

	defer resp.Body.Close()

	result, err := decodeGetInstanceMetricsByUUIDResponse(resp)
	if err != nil {
		return res, errors.Wrap(err, "decode response")
	}

	return result, nil
}

// GetInstances invokes GetInstances operation.
//
// Get one or many instances with their current status and configuration.
//
//	It's possible to filter this list by name or UUID.
//
// GET /v1/instances
func (c *Client) GetInstances(ctx context.Context, request []GetInstancesRequestID, params GetInstancesParams) (*GetInstancesResponseStatusCode, error) {
	res, err := c.sendGetInstances(ctx, request, params)
	return res, err
}

func (c *Client) sendGetInstances(ctx context.Context, request []GetInstancesRequestID, params GetInstancesParams) (res *GetInstancesResponseStatusCode, err error) {

	u := uri.Clone(c.requestURL(ctx))
	var pathParts [1]string
	pathParts[0] = "/v1/instances"
	uri.AddPathParts(u, pathParts[:]...)

	q := uri.NewQueryEncoder()
	{
		// Encode "details" parameter.
		cfg := uri.QueryParameterEncodingConfig{
			Name:    "details",
			Style:   uri.QueryStyleForm,
			Explode: true,
		}

		if err := q.EncodeParam(cfg, func(e uri.Encoder) error {
			if val, ok := params.Details.Get(); ok {
				return e.EncodeValue(conv.BoolToString(val))
			}
			return nil
		}); err != nil {
			return res, errors.Wrap(err, "encode query")
		}
	}
	{
		// Encode "metrics" parameter.
		cfg := uri.QueryParameterEncodingConfig{
			Name:    "metrics",
			Style:   uri.QueryStyleForm,
			Explode: true,
		}

		if err := q.EncodeParam(cfg, func(e uri.Encoder) error {
			if val, ok := params.Metrics.Get(); ok {
				return e.EncodeValue(conv.BoolToString(val))
			}
			return nil
		}); err != nil {
			return res, errors.Wrap(err, "encode query")
		}
	}
	u.RawQuery = q.Values().Encode()

	r, err := ht.NewRequest(ctx, "GET", u)
	if err != nil {
		return res, errors.Wrap(err, "create request")
	}
	if err := encodeGetInstancesRequest(request, r); err != nil {
		return res, errors.Wrap(err, "encode request")
	}

	{
		type bitset = [1]uint8
		var satisfied bitset
		{

			switch err := c.securityBearerToken(ctx, GetInstancesOperation, r); {
			case err == nil: // if NO error
				satisfied[0] |= 1 << 0
			case errors.Is(err, ogenerrors.ErrSkipClientSecurity):
				// Skip this security.
			default:
				return res, errors.Wrap(err, "security \"BearerToken\"")
			}
		}

		if ok := func() bool {
		nextRequirement:
			for _, requirement := range []bitset{
				{0b00000001},
			} {
				for i, mask := range requirement {
					if satisfied[i]&mask != mask {
						continue nextRequirement
					}
				}
				return true
			}
			return false
		}(); !ok {
			return res, ogenerrors.ErrSecurityRequirementIsNotSatisfied
		}
	}

	resp, err := c.cfg.Client.Do(r)
	if err != nil {
		return res, errors.Wrap(err, "do request")
	}

	defer resp.Body.Close()

	result, err := decodeGetInstancesResponse(resp)
	if err != nil {
		return res, errors.Wrap(err, "decode response")
	}

	return result, nil
}

// GetServiceGroupByUUID invokes GetServiceGroupByUUID operation.
//
// Get a specified service group by its UUID.
//
// GET /v1/services/{uuid}
func (c *Client) GetServiceGroupByUUID(ctx context.Context, params GetServiceGroupByUUIDParams) (*GetServiceGroupsResponseStatusCode, error) {
	res, err := c.sendGetServiceGroupByUUID(ctx, params)
	return res, err
}

func (c *Client) sendGetServiceGroupByUUID(ctx context.Context, params GetServiceGroupByUUIDParams) (res *GetServiceGroupsResponseStatusCode, err error) {

	u := uri.Clone(c.requestURL(ctx))
	var pathParts [2]string
	pathParts[0] = "/v1/services/"
	{
		// Encode "uuid" parameter.
		e := uri.NewPathEncoder(uri.PathEncoderConfig{
			Param:   "uuid",
			Style:   uri.PathStyleSimple,
			Explode: false,
		})
		if err := func() error {
			return e.EncodeValue(conv.StringToString(params.UUID))
		}(); err != nil {
			return res, errors.Wrap(err, "encode path")
		}
		encoded, err := e.Result()
		if err != nil {
			return res, errors.Wrap(err, "encode path")
		}
		pathParts[1] = encoded
	}
	uri.AddPathParts(u, pathParts[:]...)

	r, err := ht.NewRequest(ctx, "GET", u)
	if err != nil {
		return res, errors.Wrap(err, "create request")
	}

	{
		type bitset = [1]uint8
		var satisfied bitset
		{

			switch err := c.securityBearerToken(ctx, GetServiceGroupByUUIDOperation, r); {
			case err == nil: // if NO error
				satisfied[0] |= 1 << 0
			case errors.Is(err, ogenerrors.ErrSkipClientSecurity):
				// Skip this security.
			default:
				return res, errors.Wrap(err, "security \"BearerToken\"")
			}
		}

		if ok := func() bool {
		nextRequirement:
			for _, requirement := range []bitset{
				{0b00000001},
			} {
				for i, mask := range requirement {
					if satisfied[i]&mask != mask {
						continue nextRequirement
					}
				}
				return true
			}
			return false
		}(); !ok {
			return res, ogenerrors.ErrSecurityRequirementIsNotSatisfied
		}
	}

	resp, err := c.cfg.Client.Do(r)
	if err != nil {
		return res, errors.Wrap(err, "do request")
	}

	defer resp.Body.Close()

	result, err := decodeGetServiceGroupByUUIDResponse(resp)
	if err != nil {
		return res, errors.Wrap(err, "decode response")
	}

	return result, nil
}

// GetServiceGroups invokes GetServiceGroups operation.
//
// Get one or many service groups with their current status and configuration.
//
//	It's possible to filter this list by name or UUID.
//
// GET /v1/services
func (c *Client) GetServiceGroups(ctx context.Context, request []GetServiceGroupsRequestID, params GetServiceGroupsParams) (*GetServiceGroupsResponseStatusCode, error) {
	res, err := c.sendGetServiceGroups(ctx, request, params)
	return res, err
}

func (c *Client) sendGetServiceGroups(ctx context.Context, request []GetServiceGroupsRequestID, params GetServiceGroupsParams) (res *GetServiceGroupsResponseStatusCode, err error) {

	u := uri.Clone(c.requestURL(ctx))
	var pathParts [1]string
	pathParts[0] = "/v1/services"
	uri.AddPathParts(u, pathParts[:]...)

	q := uri.NewQueryEncoder()
	{
		// Encode "details" parameter.
		cfg := uri.QueryParameterEncodingConfig{
			Name:    "details",
			Style:   uri.QueryStyleForm,
			Explode: true,
		}

		if err := q.EncodeParam(cfg, func(e uri.Encoder) error {
			if val, ok := params.Details.Get(); ok {
				return e.EncodeValue(conv.BoolToString(val))
			}
			return nil
		}); err != nil {
			return res, errors.Wrap(err, "encode query")
		}
	}
	u.RawQuery = q.Values().Encode()

	r, err := ht.NewRequest(ctx, "GET", u)
	if err != nil {
		return res, errors.Wrap(err, "create request")
	}
	if err := encodeGetServiceGroupsRequest(request, r); err != nil {
		return res, errors.Wrap(err, "encode request")
	}

	{
		type bitset = [1]uint8
		var satisfied bitset
		{

			switch err := c.securityBearerToken(ctx, GetServiceGroupsOperation, r); {
			case err == nil: // if NO error
				satisfied[0] |= 1 << 0
			case errors.Is(err, ogenerrors.ErrSkipClientSecurity):
				// Skip this security.
			default:
				return res, errors.Wrap(err, "security \"BearerToken\"")
			}
		}

		if ok := func() bool {
		nextRequirement:
			for _, requirement := range []bitset{
				{0b00000001},
			} {
				for i, mask := range requirement {
					if satisfied[i]&mask != mask {
						continue nextRequirement
					}
				}
				return true
			}
			return false
		}(); !ok {
			return res, ogenerrors.ErrSecurityRequirementIsNotSatisfied
		}
	}

	resp, err := c.cfg.Client.Do(r)
	if err != nil {
		return res, errors.Wrap(err, "do request")
	}

	defer resp.Body.Close()

	result, err := decodeGetServiceGroupsResponse(resp)
	if err != nil {
		return res, errors.Wrap(err, "decode response")
	}

	return result, nil
}

// StartInstanceByUUID invokes StartInstanceByUUID operation.
//
// Starts previously stopped instance by its UUID or does nothing if the
//
//	instance is already running.
//
// PUT /v1/instances/{uuid}/start
func (c *Client) StartInstanceByUUID(ctx context.Context, params StartInstanceByUUIDParams) (*StartInstanceResponseStatusCode, error) {
	res, err := c.sendStartInstanceByUUID(ctx, params)
	return res, err
}

func (c *Client) sendStartInstanceByUUID(ctx context.Context, params StartInstanceByUUIDParams) (res *StartInstanceResponseStatusCode, err error) {

	u := uri.Clone(c.requestURL(ctx))
	var pathParts [3]string
	pathParts[0] = "/v1/instances/"
	{
		// Encode "uuid" parameter.
		e := uri.NewPathEncoder(uri.PathEncoderConfig{
			Param:   "uuid",
			Style:   uri.PathStyleSimple,
			Explode: false,
		})
		if err := func() error {
			return e.EncodeValue(conv.StringToString(params.UUID))
		}(); err != nil {
			return res, errors.Wrap(err, "encode path")
		}
		encoded, err := e.Result()
		if err != nil {
			return res, errors.Wrap(err, "encode path")
		}
		pathParts[1] = encoded
	}
	pathParts[2] = "/start"
	uri.AddPathParts(u, pathParts[:]...)

	r, err := ht.NewRequest(ctx, "PUT", u)
	if err != nil {
		return res, errors.Wrap(err, "create request")
	}

	{
		type bitset = [1]uint8
		var satisfied bitset
		{

			switch err := c.securityBearerToken(ctx, StartInstanceByUUIDOperation, r); {
			case err == nil: // if NO error
				satisfied[0] |= 1 << 0
			case errors.Is(err, ogenerrors.ErrSkipClientSecurity):
				// Skip this security.
			default:
				return res, errors.Wrap(err, "security \"BearerToken\"")
			}
		}

		if ok := func() bool {
		nextRequirement:
			for _, requirement := range []bitset{
				{0b00000001},
			} {
				for i, mask := range requirement {
					if satisfied[i]&mask != mask {
						continue nextRequirement
					}
				}
				return true
			}
			return false
		}(); !ok {
			return res, ogenerrors.ErrSecurityRequirementIsNotSatisfied
		}
	}

	resp, err := c.cfg.Client.Do(r)
	if err != nil {
		return res, errors.Wrap(err, "do request")
	}

	defer resp.Body.Close()

	result, err := decodeStartInstanceByUUIDResponse(resp)
	if err != nil {
		return res, errors.Wrap(err, "decode response")
	}

	return result, nil
}

// StopInstanceByUUID invokes StopInstanceByUUID operation.
//
// Stops a running instance by its UUID or does nothing if the instance is
//
//	already stopped.
//
// PUT /v1/instances/{uuid}/stop
func (c *Client) StopInstanceByUUID(ctx context.Context, params StopInstanceByUUIDParams) (*StopInstanceResponseStatusCode, error) {
	res, err := c.sendStopInstanceByUUID(ctx, params)
	return res, err
}

func (c *Client) sendStopInstanceByUUID(ctx context.Context, params StopInstanceByUUIDParams) (res *StopInstanceResponseStatusCode, err error) {

	u := uri.Clone(c.requestURL(ctx))
	var pathParts [3]string
	pathParts[0] = "/v1/instances/"
	{
		// Encode "uuid" parameter.
		e := uri.NewPathEncoder(uri.PathEncoderConfig{
			Param:   "uuid",
			Style:   uri.PathStyleSimple,
			Explode: false,
		})
		if err := func() error {
			return e.EncodeValue(conv.StringToString(params.UUID))
		}(); err != nil {
			return res, errors.Wrap(err, "encode path")
		}
		encoded, err := e.Result()
		if err != nil {
			return res, errors.Wrap(err, "encode path")
		}
		pathParts[1] = encoded
	}
	pathParts[2] = "/stop"
	uri.AddPathParts(u, pathParts[:]...)

	q := uri.NewQueryEncoder()
	{
		// Encode "force" parameter.
		cfg := uri.QueryParameterEncodingConfig{
			Name:    "force",
			Style:   uri.QueryStyleForm,
			Explode: true,
		}

		if err := q.EncodeParam(cfg, func(e uri.Encoder) error {
			if val, ok := params.Force.Get(); ok {
				return e.EncodeValue(conv.BoolToString(val))
			}
			return nil
		}); err != nil {
			return res, errors.Wrap(err, "encode query")
		}
	}
	{
		// Encode "drain_timeout_ms" parameter.
		cfg := uri.QueryParameterEncodingConfig{
			Name:    "drain_timeout_ms",
			Style:   uri.QueryStyleForm,
			Explode: true,
		}

		if err := q.EncodeParam(cfg, func(e uri.Encoder) error {
			if val, ok := params.DrainTimeoutMs.Get(); ok {
				return e.EncodeValue(conv.Uint64ToString(val))
			}
			return nil
		}); err != nil {
			return res, errors.Wrap(err, "encode query")
		}
	}
	u.RawQuery = q.Values().Encode()

	r, err := ht.NewRequest(ctx, "PUT", u)
	if err != nil {
		return res, errors.Wrap(err, "create request")
	}

	{
		type bitset = [1]uint8
		var satisfied bitset
		{

			switch err := c.securityBearerToken(ctx, StopInstanceByUUIDOperation, r); {
			case err == nil: // if NO error
				satisfied[0] |= 1 << 0
			case errors.Is(err, ogenerrors.ErrSkipClientSecurity):
				// Skip this security.
			default:
				return res, errors.Wrap(err, "security \"BearerToken\"")
			}
		}

		if ok := func() bool {
		nextRequirement:
			for _, requirement := range []bitset{
				{0b00000001},
			} {
				for i, mask := range requirement {
					if satisfied[i]&mask != mask {
						continue nextRequirement
					}
				}
				return true
			}
			return false
		}(); !ok {
			return res, ogenerrors.ErrSecurityRequirementIsNotSatisfied
		}
	}

	resp, err := c.cfg.Client.Do(r)
	if err != nil {
		return res, errors.Wrap(err, "do request")
	}

	defer resp.Body.Close()

	result, err := decodeStopInstanceByUUIDResponse(resp)
	if err != nil {
		return res, errors.Wrap(err, "decode response")
	}

	return result, nil
}

// StopInstances invokes StopInstances operation.
//
// Stops one or more running instance by their UUID(s) or name(s) or does
//
//	nothing if the instance is already stopped.
//
// PUT /v1/instances/stop
func (c *Client) StopInstances(ctx context.Context, request []StopInstancesRequestID, params StopInstancesParams) (*StopInstanceResponseStatusCode, error) {
	res, err := c.sendStopInstances(ctx, request, params)
	return res, err
}

func (c *Client) sendStopInstances(ctx context.Context, request []StopInstancesRequestID, params StopInstancesParams) (res *StopInstanceResponseStatusCode, err error) {

	u := uri.Clone(c.requestURL(ctx))
	var pathParts [1]string
	pathParts[0] = "/v1/instances/stop"
	uri.AddPathParts(u, pathParts[:]...)

	q := uri.NewQueryEncoder()
	{
		// Encode "force" parameter.
		cfg := uri.QueryParameterEncodingConfig{
			Name:    "force",
			Style:   uri.QueryStyleForm,
			Explode: true,
		}

		if err := q.EncodeParam(cfg, func(e uri.Encoder) error {
			if val, ok := params.Force.Get(); ok {
				return e.EncodeValue(conv.BoolToString(val))
			}
			return nil
		}); err != nil {
			return res, errors.Wrap(err, "encode query")
		}
	}
	{
		// Encode "drain_timeout_ms" parameter.
		cfg := uri.QueryParameterEncodingConfig{
			Name:    "drain_timeout_ms",
			Style:   uri.QueryStyleForm,
			Explode: true,
		}

		if err := q.EncodeParam(cfg, func(e uri.Encoder) error {
			if val, ok := params.DrainTimeoutMs.Get(); ok {
				return e.EncodeValue(conv.Uint64ToString(val))
			}
			return nil
		}); err != nil {
			return res, errors.Wrap(err, "encode query")
		}
	}
	u.RawQuery = q.Values().Encode()

	r, err := ht.NewRequest(ctx, "PUT", u)
	if err != nil {
		return res, errors.Wrap(err, "create request")
	}
	if err := encodeStopInstancesRequest(request, r); err != nil {
		return res, errors.Wrap(err, "encode request")
	}

	{
		type bitset = [1]uint8
		var satisfied bitset
		{

			switch err := c.securityBearerToken(ctx, StopInstancesOperation, r); {
			case err == nil: // if NO error
				satisfied[0] |= 1 << 0
			case errors.Is(err, ogenerrors.ErrSkipClientSecurity):
				// Skip this security.
			default:
				return res, errors.Wrap(err, "security \"BearerToken\"")
			}
		}

		if ok := func() bool {
		nextRequirement:
			for _, requirement := range []bitset{
				{0b00000001},
			} {
				for i, mask := range requirement {
					if satisfied[i]&mask != mask {
						continue nextRequirement
					}
				}
				return true
			}
			return false
		}(); !ok {
			return res, ogenerrors.ErrSecurityRequirementIsNotSatisfied
		}
	}

	resp, err := c.cfg.Client.Do(r)
	if err != nil {
		return res, errors.Wrap(err, "do request")
	}

	defer resp.Body.Close()

	result, err := decodeStopInstancesResponse(resp)
	if err != nil {
		return res, errors.Wrap(err, "decode response")
	}

	return result, nil
}

// WaitInstanceByUUID invokes WaitInstanceByUUID operation.
//
// Waits for an instance to reach a certain state by its UUID.
//
//	If the instance is already in the desired state, the request will return
//	immediately.  If the instance is not in the desired state, the request will
//	block until the instance reaches the desired state or the timeout is
//	reached.  If the timeout is reached, the request will fail with an error.
//	If the timeout is -1, the request will block indefinitely until the
//	instance reaches the desired state.
//
// GET /v1/instances/{uuid}/wait
func (c *Client) WaitInstanceByUUID(ctx context.Context, params WaitInstanceByUUIDParams) (*WaitInstanceResponseStatusCode, error) {
	res, err := c.sendWaitInstanceByUUID(ctx, params)
	return res, err
}

func (c *Client) sendWaitInstanceByUUID(ctx context.Context, params WaitInstanceByUUIDParams) (res *WaitInstanceResponseStatusCode, err error) {

	u := uri.Clone(c.requestURL(ctx))
	var pathParts [3]string
	pathParts[0] = "/v1/instances/"
	{
		// Encode "uuid" parameter.
		e := uri.NewPathEncoder(uri.PathEncoderConfig{
			Param:   "uuid",
			Style:   uri.PathStyleSimple,
			Explode: false,
		})
		if err := func() error {
			return e.EncodeValue(conv.StringToString(params.UUID))
		}(); err != nil {
			return res, errors.Wrap(err, "encode path")
		}
		encoded, err := e.Result()
		if err != nil {
			return res, errors.Wrap(err, "encode path")
		}
		pathParts[1] = encoded
	}
	pathParts[2] = "/wait"
	uri.AddPathParts(u, pathParts[:]...)

	q := uri.NewQueryEncoder()
	{
		// Encode "state" parameter.
		cfg := uri.QueryParameterEncodingConfig{
			Name:    "state",
			Style:   uri.QueryStyleForm,
			Explode: true,
		}

		if err := q.EncodeParam(cfg, func(e uri.Encoder) error {
			if val, ok := params.State.Get(); ok {
				return e.EncodeValue(conv.StringToString(string(val)))
			}
			return nil
		}); err != nil {
			return res, errors.Wrap(err, "encode query")
		}
	}
	{
		// Encode "timeout_ms" parameter.
		cfg := uri.QueryParameterEncodingConfig{
			Name:    "timeout_ms",
			Style:   uri.QueryStyleForm,
			Explode: true,
		}

		if err := q.EncodeParam(cfg, func(e uri.Encoder) error {
			if val, ok := params.TimeoutMs.Get(); ok {
				return e.EncodeValue(conv.Int64ToString(val))
			}
			return nil
		}); err != nil {
			return res, errors.Wrap(err, "encode query")
		}
	}
	u.RawQuery = q.Values().Encode()

	r, err := ht.NewRequest(ctx, "GET", u)
	if err != nil {
		return res, errors.Wrap(err, "create request")
	}

	{
		type bitset = [1]uint8
		var satisfied bitset
		{

			switch err := c.securityBearerToken(ctx, WaitInstanceByUUIDOperation, r); {
			case err == nil: // if NO error
				satisfied[0] |= 1 << 0
			case errors.Is(err, ogenerrors.ErrSkipClientSecurity):
				// Skip this security.
			default:
				return res, errors.Wrap(err, "security \"BearerToken\"")
			}
		}

		if ok := func() bool {
		nextRequirement:
			for _, requirement := range []bitset{
				{0b00000001},
			} {
				for i, mask := range requirement {
					if satisfied[i]&mask != mask {
						continue nextRequirement
					}
				}
				return true
			}
			return false
		}(); !ok {
			return res, ogenerrors.ErrSecurityRequirementIsNotSatisfied
		}
	}

	resp, err := c.cfg.Client.Do(r)
	if err != nil {
		return res, errors.Wrap(err, "do request")
	}

	defer resp.Body.Close()

	result, err := decodeWaitInstanceByUUIDResponse(resp)
	if err != nil {
		return res, errors.Wrap(err, "decode response")
	}

	return result, nil
}

// WaitInstances invokes WaitInstances operation.
//
// Waits for an instance to reach a certain state by its UUID or name.
//
//	If the instance is already in the desired state, the request will return
//	immediately.  If the instance is not in the desired state, the request will
//	block until the instance reaches the desired state or the timeout is
//	reached.  If the timeout is reached, the request will fail with an error.
//	If the timeout is -1, the request will block indefinitely until the
//	instance reaches the desired state.
//
// GET /v1/instances/wait
func (c *Client) WaitInstances(ctx context.Context, request []WaitInstancesRequestID, params WaitInstancesParams) (*WaitInstanceResponseStatusCode, error) {
	res, err := c.sendWaitInstances(ctx, request, params)
	return res, err
}

func (c *Client) sendWaitInstances(ctx context.Context, request []WaitInstancesRequestID, params WaitInstancesParams) (res *WaitInstanceResponseStatusCode, err error) {

	u := uri.Clone(c.requestURL(ctx))
	var pathParts [1]string
	pathParts[0] = "/v1/instances/wait"
	uri.AddPathParts(u, pathParts[:]...)

	q := uri.NewQueryEncoder()
	{
		// Encode "state" parameter.
		cfg := uri.QueryParameterEncodingConfig{
			Name:    "state",
			Style:   uri.QueryStyleForm,
			Explode: true,
		}

		if err := q.EncodeParam(cfg, func(e uri.Encoder) error {
			if val, ok := params.State.Get(); ok {
				return e.EncodeValue(conv.StringToString(string(val)))
			}
			return nil
		}); err != nil {
			return res, errors.Wrap(err, "encode query")
		}
	}
	{
		// Encode "timeout_ms" parameter.
		cfg := uri.QueryParameterEncodingConfig{
			Name:    "timeout_ms",
			Style:   uri.QueryStyleForm,
			Explode: true,
		}

		if err := q.EncodeParam(cfg, func(e uri.Encoder) error {
			if val, ok := params.TimeoutMs.Get(); ok {
				return e.EncodeValue(conv.Int64ToString(val))
			}
			return nil
		}); err != nil {
			return res, errors.Wrap(err, "encode query")
		}
	}
	u.RawQuery = q.Values().Encode()

	r, err := ht.NewRequest(ctx, "GET", u)
	if err != nil {
		return res, errors.Wrap(err, "create request")
	}
	if err := encodeWaitInstancesRequest(request, r); err != nil {
		return res, errors.Wrap(err, "encode request")
	}

	{
		type bitset = [1]uint8
		var satisfied bitset
		{

			switch err := c.securityBearerToken(ctx, WaitInstancesOperation, r); {
			case err == nil: // if NO error
				satisfied[0] |= 1 << 0
			case errors.Is(err, ogenerrors.ErrSkipClientSecurity):
				// Skip this security.
			default:
				return res, errors.Wrap(err, "security \"BearerToken\"")
			}
		}

		if ok := func() bool {
		nextRequirement:
			for _, requirement := range []bitset{
				{0b00000001},
			} {
				for i, mask := range requirement {
					if satisfied[i]&mask != mask {
						continue nextRequirement
					}
				}
				return true
			}
			return false
		}(); !ok {
			return res, ogenerrors.ErrSecurityRequirementIsNotSatisfied
		}
	}

	resp, err := c.cfg.Client.Do(r)
	if err != nil {
		return res, errors.Wrap(err, "do request")
	}

	defer resp.Body.Close()

	result, err := decodeWaitInstancesResponse(resp)
	if err != nil {
		return res, errors.Wrap(err, "decode response")
	}

	return result, nil
}
