// Code generated by ogen, DO NOT EDIT.

package platform

// OperationName is the ogen operation name
type OperationName = string

const (
	CreateInstanceOperation           OperationName = "CreateInstance"
	DeleteInstanceByUUIDOperation     OperationName = "DeleteInstanceByUUID"
	GetImageByDigestOperation         OperationName = "GetImageByDigest"
	GetImageByTagOperation            OperationName = "GetImageByTag"
	GetInstanceByUUIDOperation        OperationName = "GetInstanceByUUID"
	GetInstanceLogsOperation          OperationName = "GetInstanceLogs"
	GetInstanceLogsByUUIDOperation    OperationName = "GetInstanceLogsByUUID"
	GetInstanceMetricsOperation       OperationName = "GetInstanceMetrics"
	GetInstanceMetricsByUUIDOperation OperationName = "GetInstanceMetricsByUUID"
	GetInstancesOperation             OperationName = "GetInstances"
	StartInstanceByUUIDOperation      OperationName = "StartInstanceByUUID"
	StopInstanceByUUIDOperation       OperationName = "StopInstanceByUUID"
	StopInstancesOperation            OperationName = "StopInstances"
	WaitInstanceByUUIDOperation       OperationName = "WaitInstanceByUUID"
	WaitInstancesOperation            OperationName = "WaitInstances"
)
