// Code generated by ogen, DO NOT EDIT.

package platform

// OperationName is the ogen operation name
type OperationName = string

const (
	CreateCertificateOperation        OperationName = "CreateCertificate"
	CreateInstanceOperation           OperationName = "CreateInstance"
	CreateServiceGroupOperation       OperationName = "CreateServiceGroup"
	DeleteCertificateByUUIDOperation  OperationName = "DeleteCertificateByUUID"
	DeleteCertificatesOperation       OperationName = "DeleteCertificates"
	DeleteInstanceByUUIDOperation     OperationName = "DeleteInstanceByUUID"
	DeleteServiceGroupByUUIDOperation OperationName = "DeleteServiceGroupByUUID"
	DeleteServiceGroupsOperation      OperationName = "DeleteServiceGroups"
	GetCertificateByUUIDOperation     OperationName = "GetCertificateByUUID"
	GetCertificatesOperation          OperationName = "GetCertificates"
	GetImageByDigestOperation         OperationName = "GetImageByDigest"
	GetImageByTagOperation            OperationName = "GetImageByTag"
	GetInstanceByUUIDOperation        OperationName = "GetInstanceByUUID"
	GetInstanceLogsOperation          OperationName = "GetInstanceLogs"
	GetInstanceLogsByUUIDOperation    OperationName = "GetInstanceLogsByUUID"
	GetInstanceMetricsOperation       OperationName = "GetInstanceMetrics"
	GetInstanceMetricsByUUIDOperation OperationName = "GetInstanceMetricsByUUID"
	GetInstancesOperation             OperationName = "GetInstances"
	GetServiceGroupByUUIDOperation    OperationName = "GetServiceGroupByUUID"
	GetServiceGroupsOperation         OperationName = "GetServiceGroups"
	StartInstanceByUUIDOperation      OperationName = "StartInstanceByUUID"
	StopInstanceByUUIDOperation       OperationName = "StopInstanceByUUID"
	StopInstancesOperation            OperationName = "StopInstances"
	WaitInstanceByUUIDOperation       OperationName = "WaitInstanceByUUID"
	WaitInstancesOperation            OperationName = "WaitInstances"
)
