// Code generated by ogen, DO NOT EDIT.

package platform

import (
	"context"
	"net/url"
	"strings"

	"github.com/go-faster/errors"

	"github.com/ogen-go/ogen/conv"
	ht "github.com/ogen-go/ogen/http"
	"github.com/ogen-go/ogen/ogenerrors"
	"github.com/ogen-go/ogen/uri"
)

func trimTrailingSlashes(u *url.URL) {
	u.Path = strings.TrimRight(u.Path, "/")
	u.RawPath = strings.TrimRight(u.RawPath, "/")
}

// Invoker invokes operations described by OpenAPI v3 specification.
type Invoker interface {
	// CreateInstance invokes CreateInstance operation.
	//
	// Creates one or more new instances.
	//
	// POST /v1/instances
	CreateInstance(ctx context.Context, request *CreateInstanceRequest) (*CreateInstanceResponse, error)
	// DeleteInstanceByUUID invokes DeleteInstanceByUUID operation.
	//
	// Delete a specified instance by its UUID.  After this call the UUID of the
	//  instances are no longer valid.  If the instances are currently running,
	//  they are force stopped.
	//
	// DELETE /v1/instances/{uuid}
	DeleteInstanceByUUID(ctx context.Context, params DeleteInstanceByUUIDParams) (*DeleteInstancesResponse, error)
	// GetImageByDigest invokes GetImageByDigest operation.
	//
	// GetImageByDigest retrieves an image by its digest.
	//
	// GET /v1/images/digest/{digest}
	GetImageByDigest(ctx context.Context, params GetImageByDigestParams) (*GetImageResponse, error)
	// GetImageByTag invokes GetImageByTag operation.
	//
	// GetImageByTag retrieves an image by its tag.
	//
	// GET /v1/images/tag/{tag}
	GetImageByTag(ctx context.Context, params GetImageByTagParams) (*GetImageResponse, error)
	// GetInstanceByUUID invokes GetInstanceByUUID operation.
	//
	// Get a single instance by its ID which can either be its name or UUID.
	//
	// GET /v1/instances/{uuid}
	GetInstanceByUUID(ctx context.Context, params GetInstanceByUUIDParams) (*GetInstancesResponse, error)
	// GetInstanceLogs invokes GetInstanceLogs operation.
	//
	// Retrieve the logs of an instance by its UUID or name.
	//
	// PUT /v1/instances/logs
	GetInstanceLogs(ctx context.Context, request *GetInstanceLogsRequest) (*GetInstanceLogsResponse, error)
	// GetInstanceLogsByUUID invokes GetInstanceLogsByUUID operation.
	//
	// Retrieve the logs of an instance by its UUID.
	//
	// PUT /v1/instances/{uuid}/logs
	GetInstanceLogsByUUID(ctx context.Context, params GetInstanceLogsByUUIDParams) (*GetInstanceLogsResponse, error)
	// GetInstanceMetrics invokes GetInstanceMetrics operation.
	//
	// Get the metrics of an instance by its UUID or name.
	//
	// PUT /v1/instances/metrics
	GetInstanceMetrics(ctx context.Context, request *GetInstanceMetricsRequest) (*GetInstanceMetricsResponse, error)
	// GetInstanceMetricsByUUID invokes GetInstanceMetricsByUUID operation.
	//
	// Get the metrics of an instance by its UUID.
	//
	// PUT /v1/instances/{uuid}/metrics
	GetInstanceMetricsByUUID(ctx context.Context, params GetInstanceMetricsByUUIDParams) (*GetInstanceMetricsResponse, error)
	// GetInstances invokes GetInstances operation.
	//
	// Get one or many instances with their current status and configuration.
	//  It's possible to filter this list by name or UUID.
	//
	// GET /v1/instances
	GetInstances(ctx context.Context, params GetInstancesParams) (*GetInstancesResponse, error)
	// StartInstanceByUUID invokes StartInstanceByUUID operation.
	//
	// Starts previously stopped instance by its UUID or does nothing if the
	//  instance is already running.
	//
	// PUT /v1/instances/{uuid}/start
	StartInstanceByUUID(ctx context.Context, params StartInstanceByUUIDParams) (*StartInstanceResponse, error)
	// StopInstanceByUUID invokes StopInstanceByUUID operation.
	//
	// Stops a running instance by its UUID or does nothing if the instance is
	//  already stopped.
	//
	// PUT /v1/instances/{uuid}/stop
	StopInstanceByUUID(ctx context.Context, params StopInstanceByUUIDParams) (*StopInstanceResponse, error)
	// StopInstances invokes StopInstances operation.
	//
	// Stops one or more running instance by their UUID(s) or name(s) or does
	//  nothing if the instance is already stopped.
	//
	// PUT /v1/instances/stop
	StopInstances(ctx context.Context, request []StopInstancesRequestID, params StopInstancesParams) (*StopInstanceResponse, error)
	// WaitInstanceByUUID invokes WaitInstanceByUUID operation.
	//
	// Waits for an instance to reach a certain state by its UUID.
	//
	//  If the instance is already in the desired state, the request will return
	//  immediately.  If the instance is not in the desired state, the request will
	//  block until the instance reaches the desired state or the timeout is
	//  reached.  If the timeout is reached, the request will fail with an error.
	//  If the timeout is -1, the request will block indefinitely until the
	//  instance reaches the desired state.
	//
	// GET /v1/instances/{uuid}/wait
	WaitInstanceByUUID(ctx context.Context, params WaitInstanceByUUIDParams) (*WaitInstanceResponse, error)
	// WaitInstances invokes WaitInstances operation.
	//
	// Waits for an instance to reach a certain state by its UUID or name.
	//
	//  If the instance is already in the desired state, the request will return
	//  immediately.  If the instance is not in the desired state, the request will
	//  block until the instance reaches the desired state or the timeout is
	//  reached.  If the timeout is reached, the request will fail with an error.
	//  If the timeout is -1, the request will block indefinitely until the
	//  instance reaches the desired state.
	//
	// GET /v1/instances/wait
	WaitInstances(ctx context.Context, request *WaitInstancesRequest) (*WaitInstanceResponse, error)
}

// Client implements OAS client.
type Client struct {
	serverURL *url.URL
	sec       SecuritySource
	baseClient
}

// NewClient initializes new Client defined by OAS.
func NewClient(serverURL string, sec SecuritySource, opts ...ClientOption) (*Client, error) {
	u, err := url.Parse(serverURL)
	if err != nil {
		return nil, err
	}
	trimTrailingSlashes(u)

	c, err := newClientConfig(opts...).baseClient()
	if err != nil {
		return nil, err
	}
	return &Client{
		serverURL:  u,
		sec:        sec,
		baseClient: c,
	}, nil
}

type serverURLKey struct{}

// WithServerURL sets context key to override server URL.
func WithServerURL(ctx context.Context, u *url.URL) context.Context {
	return context.WithValue(ctx, serverURLKey{}, u)
}

func (c *Client) requestURL(ctx context.Context) *url.URL {
	u, ok := ctx.Value(serverURLKey{}).(*url.URL)
	if !ok {
		return c.serverURL
	}
	return u
}

// CreateInstance invokes CreateInstance operation.
//
// Creates one or more new instances.
//
// POST /v1/instances
func (c *Client) CreateInstance(ctx context.Context, request *CreateInstanceRequest) (*CreateInstanceResponse, error) {
	res, err := c.sendCreateInstance(ctx, request)
	return res, err
}

func (c *Client) sendCreateInstance(ctx context.Context, request *CreateInstanceRequest) (res *CreateInstanceResponse, err error) {

	u := uri.Clone(c.requestURL(ctx))
	var pathParts [1]string
	pathParts[0] = "/v1/instances"
	uri.AddPathParts(u, pathParts[:]...)

	r, err := ht.NewRequest(ctx, "POST", u)
	if err != nil {
		return res, errors.Wrap(err, "create request")
	}
	if err := encodeCreateInstanceRequest(request, r); err != nil {
		return res, errors.Wrap(err, "encode request")
	}

	{
		type bitset = [1]uint8
		var satisfied bitset
		{

			switch err := c.securityBearerToken(ctx, CreateInstanceOperation, r); {
			case err == nil: // if NO error
				satisfied[0] |= 1 << 0
			case errors.Is(err, ogenerrors.ErrSkipClientSecurity):
				// Skip this security.
			default:
				return res, errors.Wrap(err, "security \"BearerToken\"")
			}
		}

		if ok := func() bool {
		nextRequirement:
			for _, requirement := range []bitset{
				{0b00000001},
			} {
				for i, mask := range requirement {
					if satisfied[i]&mask != mask {
						continue nextRequirement
					}
				}
				return true
			}
			return false
		}(); !ok {
			return res, ogenerrors.ErrSecurityRequirementIsNotSatisfied
		}
	}

	resp, err := c.cfg.Client.Do(r)
	if err != nil {
		return res, errors.Wrap(err, "do request")
	}
	defer resp.Body.Close()

	result, err := decodeCreateInstanceResponse(resp)
	if err != nil {
		return res, errors.Wrap(err, "decode response")
	}

	return result, nil
}

// DeleteInstanceByUUID invokes DeleteInstanceByUUID operation.
//
// Delete a specified instance by its UUID.  After this call the UUID of the
//
//	instances are no longer valid.  If the instances are currently running,
//	they are force stopped.
//
// DELETE /v1/instances/{uuid}
func (c *Client) DeleteInstanceByUUID(ctx context.Context, params DeleteInstanceByUUIDParams) (*DeleteInstancesResponse, error) {
	res, err := c.sendDeleteInstanceByUUID(ctx, params)
	return res, err
}

func (c *Client) sendDeleteInstanceByUUID(ctx context.Context, params DeleteInstanceByUUIDParams) (res *DeleteInstancesResponse, err error) {

	u := uri.Clone(c.requestURL(ctx))
	var pathParts [2]string
	pathParts[0] = "/v1/instances/"
	{
		// Encode "uuid" parameter.
		e := uri.NewPathEncoder(uri.PathEncoderConfig{
			Param:   "uuid",
			Style:   uri.PathStyleSimple,
			Explode: false,
		})
		if err := func() error {
			return e.EncodeValue(conv.StringToString(params.UUID))
		}(); err != nil {
			return res, errors.Wrap(err, "encode path")
		}
		encoded, err := e.Result()
		if err != nil {
			return res, errors.Wrap(err, "encode path")
		}
		pathParts[1] = encoded
	}
	uri.AddPathParts(u, pathParts[:]...)

	r, err := ht.NewRequest(ctx, "DELETE", u)
	if err != nil {
		return res, errors.Wrap(err, "create request")
	}

	{
		type bitset = [1]uint8
		var satisfied bitset
		{

			switch err := c.securityBearerToken(ctx, DeleteInstanceByUUIDOperation, r); {
			case err == nil: // if NO error
				satisfied[0] |= 1 << 0
			case errors.Is(err, ogenerrors.ErrSkipClientSecurity):
				// Skip this security.
			default:
				return res, errors.Wrap(err, "security \"BearerToken\"")
			}
		}

		if ok := func() bool {
		nextRequirement:
			for _, requirement := range []bitset{
				{0b00000001},
			} {
				for i, mask := range requirement {
					if satisfied[i]&mask != mask {
						continue nextRequirement
					}
				}
				return true
			}
			return false
		}(); !ok {
			return res, ogenerrors.ErrSecurityRequirementIsNotSatisfied
		}
	}

	resp, err := c.cfg.Client.Do(r)
	if err != nil {
		return res, errors.Wrap(err, "do request")
	}
	defer resp.Body.Close()

	result, err := decodeDeleteInstanceByUUIDResponse(resp)
	if err != nil {
		return res, errors.Wrap(err, "decode response")
	}

	return result, nil
}

// GetImageByDigest invokes GetImageByDigest operation.
//
// GetImageByDigest retrieves an image by its digest.
//
// GET /v1/images/digest/{digest}
func (c *Client) GetImageByDigest(ctx context.Context, params GetImageByDigestParams) (*GetImageResponse, error) {
	res, err := c.sendGetImageByDigest(ctx, params)
	return res, err
}

func (c *Client) sendGetImageByDigest(ctx context.Context, params GetImageByDigestParams) (res *GetImageResponse, err error) {

	u := uri.Clone(c.requestURL(ctx))
	var pathParts [2]string
	pathParts[0] = "/v1/images/digest/"
	{
		// Encode "digest" parameter.
		e := uri.NewPathEncoder(uri.PathEncoderConfig{
			Param:   "digest",
			Style:   uri.PathStyleSimple,
			Explode: false,
		})
		if err := func() error {
			return e.EncodeValue(conv.StringToString(params.Digest))
		}(); err != nil {
			return res, errors.Wrap(err, "encode path")
		}
		encoded, err := e.Result()
		if err != nil {
			return res, errors.Wrap(err, "encode path")
		}
		pathParts[1] = encoded
	}
	uri.AddPathParts(u, pathParts[:]...)

	r, err := ht.NewRequest(ctx, "GET", u)
	if err != nil {
		return res, errors.Wrap(err, "create request")
	}

	{
		type bitset = [1]uint8
		var satisfied bitset
		{

			switch err := c.securityBearerToken(ctx, GetImageByDigestOperation, r); {
			case err == nil: // if NO error
				satisfied[0] |= 1 << 0
			case errors.Is(err, ogenerrors.ErrSkipClientSecurity):
				// Skip this security.
			default:
				return res, errors.Wrap(err, "security \"BearerToken\"")
			}
		}

		if ok := func() bool {
		nextRequirement:
			for _, requirement := range []bitset{
				{0b00000001},
			} {
				for i, mask := range requirement {
					if satisfied[i]&mask != mask {
						continue nextRequirement
					}
				}
				return true
			}
			return false
		}(); !ok {
			return res, ogenerrors.ErrSecurityRequirementIsNotSatisfied
		}
	}

	resp, err := c.cfg.Client.Do(r)
	if err != nil {
		return res, errors.Wrap(err, "do request")
	}
	defer resp.Body.Close()

	result, err := decodeGetImageByDigestResponse(resp)
	if err != nil {
		return res, errors.Wrap(err, "decode response")
	}

	return result, nil
}

// GetImageByTag invokes GetImageByTag operation.
//
// GetImageByTag retrieves an image by its tag.
//
// GET /v1/images/tag/{tag}
func (c *Client) GetImageByTag(ctx context.Context, params GetImageByTagParams) (*GetImageResponse, error) {
	res, err := c.sendGetImageByTag(ctx, params)
	return res, err
}

func (c *Client) sendGetImageByTag(ctx context.Context, params GetImageByTagParams) (res *GetImageResponse, err error) {

	u := uri.Clone(c.requestURL(ctx))
	var pathParts [2]string
	pathParts[0] = "/v1/images/tag/"
	{
		// Encode "tag" parameter.
		e := uri.NewPathEncoder(uri.PathEncoderConfig{
			Param:   "tag",
			Style:   uri.PathStyleSimple,
			Explode: false,
		})
		if err := func() error {
			return e.EncodeValue(conv.StringToString(params.Tag))
		}(); err != nil {
			return res, errors.Wrap(err, "encode path")
		}
		encoded, err := e.Result()
		if err != nil {
			return res, errors.Wrap(err, "encode path")
		}
		pathParts[1] = encoded
	}
	uri.AddPathParts(u, pathParts[:]...)

	r, err := ht.NewRequest(ctx, "GET", u)
	if err != nil {
		return res, errors.Wrap(err, "create request")
	}

	{
		type bitset = [1]uint8
		var satisfied bitset
		{

			switch err := c.securityBearerToken(ctx, GetImageByTagOperation, r); {
			case err == nil: // if NO error
				satisfied[0] |= 1 << 0
			case errors.Is(err, ogenerrors.ErrSkipClientSecurity):
				// Skip this security.
			default:
				return res, errors.Wrap(err, "security \"BearerToken\"")
			}
		}

		if ok := func() bool {
		nextRequirement:
			for _, requirement := range []bitset{
				{0b00000001},
			} {
				for i, mask := range requirement {
					if satisfied[i]&mask != mask {
						continue nextRequirement
					}
				}
				return true
			}
			return false
		}(); !ok {
			return res, ogenerrors.ErrSecurityRequirementIsNotSatisfied
		}
	}

	resp, err := c.cfg.Client.Do(r)
	if err != nil {
		return res, errors.Wrap(err, "do request")
	}
	defer resp.Body.Close()

	result, err := decodeGetImageByTagResponse(resp)
	if err != nil {
		return res, errors.Wrap(err, "decode response")
	}

	return result, nil
}

// GetInstanceByUUID invokes GetInstanceByUUID operation.
//
// Get a single instance by its ID which can either be its name or UUID.
//
// GET /v1/instances/{uuid}
func (c *Client) GetInstanceByUUID(ctx context.Context, params GetInstanceByUUIDParams) (*GetInstancesResponse, error) {
	res, err := c.sendGetInstanceByUUID(ctx, params)
	return res, err
}

func (c *Client) sendGetInstanceByUUID(ctx context.Context, params GetInstanceByUUIDParams) (res *GetInstancesResponse, err error) {

	u := uri.Clone(c.requestURL(ctx))
	var pathParts [2]string
	pathParts[0] = "/v1/instances/"
	{
		// Encode "uuid" parameter.
		e := uri.NewPathEncoder(uri.PathEncoderConfig{
			Param:   "uuid",
			Style:   uri.PathStyleSimple,
			Explode: false,
		})
		if err := func() error {
			return e.EncodeValue(conv.StringToString(params.UUID))
		}(); err != nil {
			return res, errors.Wrap(err, "encode path")
		}
		encoded, err := e.Result()
		if err != nil {
			return res, errors.Wrap(err, "encode path")
		}
		pathParts[1] = encoded
	}
	uri.AddPathParts(u, pathParts[:]...)

	r, err := ht.NewRequest(ctx, "GET", u)
	if err != nil {
		return res, errors.Wrap(err, "create request")
	}

	{
		type bitset = [1]uint8
		var satisfied bitset
		{

			switch err := c.securityBearerToken(ctx, GetInstanceByUUIDOperation, r); {
			case err == nil: // if NO error
				satisfied[0] |= 1 << 0
			case errors.Is(err, ogenerrors.ErrSkipClientSecurity):
				// Skip this security.
			default:
				return res, errors.Wrap(err, "security \"BearerToken\"")
			}
		}

		if ok := func() bool {
		nextRequirement:
			for _, requirement := range []bitset{
				{0b00000001},
			} {
				for i, mask := range requirement {
					if satisfied[i]&mask != mask {
						continue nextRequirement
					}
				}
				return true
			}
			return false
		}(); !ok {
			return res, ogenerrors.ErrSecurityRequirementIsNotSatisfied
		}
	}

	resp, err := c.cfg.Client.Do(r)
	if err != nil {
		return res, errors.Wrap(err, "do request")
	}
	defer resp.Body.Close()

	result, err := decodeGetInstanceByUUIDResponse(resp)
	if err != nil {
		return res, errors.Wrap(err, "decode response")
	}

	return result, nil
}

// GetInstanceLogs invokes GetInstanceLogs operation.
//
// Retrieve the logs of an instance by its UUID or name.
//
// PUT /v1/instances/logs
func (c *Client) GetInstanceLogs(ctx context.Context, request *GetInstanceLogsRequest) (*GetInstanceLogsResponse, error) {
	res, err := c.sendGetInstanceLogs(ctx, request)
	return res, err
}

func (c *Client) sendGetInstanceLogs(ctx context.Context, request *GetInstanceLogsRequest) (res *GetInstanceLogsResponse, err error) {

	u := uri.Clone(c.requestURL(ctx))
	var pathParts [1]string
	pathParts[0] = "/v1/instances/logs"
	uri.AddPathParts(u, pathParts[:]...)

	r, err := ht.NewRequest(ctx, "PUT", u)
	if err != nil {
		return res, errors.Wrap(err, "create request")
	}
	if err := encodeGetInstanceLogsRequest(request, r); err != nil {
		return res, errors.Wrap(err, "encode request")
	}

	{
		type bitset = [1]uint8
		var satisfied bitset
		{

			switch err := c.securityBearerToken(ctx, GetInstanceLogsOperation, r); {
			case err == nil: // if NO error
				satisfied[0] |= 1 << 0
			case errors.Is(err, ogenerrors.ErrSkipClientSecurity):
				// Skip this security.
			default:
				return res, errors.Wrap(err, "security \"BearerToken\"")
			}
		}

		if ok := func() bool {
		nextRequirement:
			for _, requirement := range []bitset{
				{0b00000001},
			} {
				for i, mask := range requirement {
					if satisfied[i]&mask != mask {
						continue nextRequirement
					}
				}
				return true
			}
			return false
		}(); !ok {
			return res, ogenerrors.ErrSecurityRequirementIsNotSatisfied
		}
	}

	resp, err := c.cfg.Client.Do(r)
	if err != nil {
		return res, errors.Wrap(err, "do request")
	}
	defer resp.Body.Close()

	result, err := decodeGetInstanceLogsResponse(resp)
	if err != nil {
		return res, errors.Wrap(err, "decode response")
	}

	return result, nil
}

// GetInstanceLogsByUUID invokes GetInstanceLogsByUUID operation.
//
// Retrieve the logs of an instance by its UUID.
//
// PUT /v1/instances/{uuid}/logs
func (c *Client) GetInstanceLogsByUUID(ctx context.Context, params GetInstanceLogsByUUIDParams) (*GetInstanceLogsResponse, error) {
	res, err := c.sendGetInstanceLogsByUUID(ctx, params)
	return res, err
}

func (c *Client) sendGetInstanceLogsByUUID(ctx context.Context, params GetInstanceLogsByUUIDParams) (res *GetInstanceLogsResponse, err error) {

	u := uri.Clone(c.requestURL(ctx))
	var pathParts [3]string
	pathParts[0] = "/v1/instances/"
	{
		// Encode "uuid" parameter.
		e := uri.NewPathEncoder(uri.PathEncoderConfig{
			Param:   "uuid",
			Style:   uri.PathStyleSimple,
			Explode: false,
		})
		if err := func() error {
			return e.EncodeValue(conv.StringToString(params.UUID))
		}(); err != nil {
			return res, errors.Wrap(err, "encode path")
		}
		encoded, err := e.Result()
		if err != nil {
			return res, errors.Wrap(err, "encode path")
		}
		pathParts[1] = encoded
	}
	pathParts[2] = "/logs"
	uri.AddPathParts(u, pathParts[:]...)

	q := uri.NewQueryEncoder()
	{
		// Encode "offset" parameter.
		cfg := uri.QueryParameterEncodingConfig{
			Name:    "offset",
			Style:   uri.QueryStyleForm,
			Explode: true,
		}

		if err := q.EncodeParam(cfg, func(e uri.Encoder) error {
			if val, ok := params.Offset.Get(); ok {
				return e.EncodeValue(conv.Uint64ToString(val))
			}
			return nil
		}); err != nil {
			return res, errors.Wrap(err, "encode query")
		}
	}
	{
		// Encode "limit" parameter.
		cfg := uri.QueryParameterEncodingConfig{
			Name:    "limit",
			Style:   uri.QueryStyleForm,
			Explode: true,
		}

		if err := q.EncodeParam(cfg, func(e uri.Encoder) error {
			if val, ok := params.Limit.Get(); ok {
				return e.EncodeValue(conv.Int64ToString(val))
			}
			return nil
		}); err != nil {
			return res, errors.Wrap(err, "encode query")
		}
	}
	u.RawQuery = q.Values().Encode()

	r, err := ht.NewRequest(ctx, "PUT", u)
	if err != nil {
		return res, errors.Wrap(err, "create request")
	}

	{
		type bitset = [1]uint8
		var satisfied bitset
		{

			switch err := c.securityBearerToken(ctx, GetInstanceLogsByUUIDOperation, r); {
			case err == nil: // if NO error
				satisfied[0] |= 1 << 0
			case errors.Is(err, ogenerrors.ErrSkipClientSecurity):
				// Skip this security.
			default:
				return res, errors.Wrap(err, "security \"BearerToken\"")
			}
		}

		if ok := func() bool {
		nextRequirement:
			for _, requirement := range []bitset{
				{0b00000001},
			} {
				for i, mask := range requirement {
					if satisfied[i]&mask != mask {
						continue nextRequirement
					}
				}
				return true
			}
			return false
		}(); !ok {
			return res, ogenerrors.ErrSecurityRequirementIsNotSatisfied
		}
	}

	resp, err := c.cfg.Client.Do(r)
	if err != nil {
		return res, errors.Wrap(err, "do request")
	}
	defer resp.Body.Close()

	result, err := decodeGetInstanceLogsByUUIDResponse(resp)
	if err != nil {
		return res, errors.Wrap(err, "decode response")
	}

	return result, nil
}

// GetInstanceMetrics invokes GetInstanceMetrics operation.
//
// Get the metrics of an instance by its UUID or name.
//
// PUT /v1/instances/metrics
func (c *Client) GetInstanceMetrics(ctx context.Context, request *GetInstanceMetricsRequest) (*GetInstanceMetricsResponse, error) {
	res, err := c.sendGetInstanceMetrics(ctx, request)
	return res, err
}

func (c *Client) sendGetInstanceMetrics(ctx context.Context, request *GetInstanceMetricsRequest) (res *GetInstanceMetricsResponse, err error) {

	u := uri.Clone(c.requestURL(ctx))
	var pathParts [1]string
	pathParts[0] = "/v1/instances/metrics"
	uri.AddPathParts(u, pathParts[:]...)

	r, err := ht.NewRequest(ctx, "PUT", u)
	if err != nil {
		return res, errors.Wrap(err, "create request")
	}
	if err := encodeGetInstanceMetricsRequest(request, r); err != nil {
		return res, errors.Wrap(err, "encode request")
	}

	{
		type bitset = [1]uint8
		var satisfied bitset
		{

			switch err := c.securityBearerToken(ctx, GetInstanceMetricsOperation, r); {
			case err == nil: // if NO error
				satisfied[0] |= 1 << 0
			case errors.Is(err, ogenerrors.ErrSkipClientSecurity):
				// Skip this security.
			default:
				return res, errors.Wrap(err, "security \"BearerToken\"")
			}
		}

		if ok := func() bool {
		nextRequirement:
			for _, requirement := range []bitset{
				{0b00000001},
			} {
				for i, mask := range requirement {
					if satisfied[i]&mask != mask {
						continue nextRequirement
					}
				}
				return true
			}
			return false
		}(); !ok {
			return res, ogenerrors.ErrSecurityRequirementIsNotSatisfied
		}
	}

	resp, err := c.cfg.Client.Do(r)
	if err != nil {
		return res, errors.Wrap(err, "do request")
	}
	defer resp.Body.Close()

	result, err := decodeGetInstanceMetricsResponse(resp)
	if err != nil {
		return res, errors.Wrap(err, "decode response")
	}

	return result, nil
}

// GetInstanceMetricsByUUID invokes GetInstanceMetricsByUUID operation.
//
// Get the metrics of an instance by its UUID.
//
// PUT /v1/instances/{uuid}/metrics
func (c *Client) GetInstanceMetricsByUUID(ctx context.Context, params GetInstanceMetricsByUUIDParams) (*GetInstanceMetricsResponse, error) {
	res, err := c.sendGetInstanceMetricsByUUID(ctx, params)
	return res, err
}

func (c *Client) sendGetInstanceMetricsByUUID(ctx context.Context, params GetInstanceMetricsByUUIDParams) (res *GetInstanceMetricsResponse, err error) {

	u := uri.Clone(c.requestURL(ctx))
	var pathParts [3]string
	pathParts[0] = "/v1/instances/"
	{
		// Encode "uuid" parameter.
		e := uri.NewPathEncoder(uri.PathEncoderConfig{
			Param:   "uuid",
			Style:   uri.PathStyleSimple,
			Explode: false,
		})
		if err := func() error {
			return e.EncodeValue(conv.StringToString(params.UUID))
		}(); err != nil {
			return res, errors.Wrap(err, "encode path")
		}
		encoded, err := e.Result()
		if err != nil {
			return res, errors.Wrap(err, "encode path")
		}
		pathParts[1] = encoded
	}
	pathParts[2] = "/metrics"
	uri.AddPathParts(u, pathParts[:]...)

	r, err := ht.NewRequest(ctx, "PUT", u)
	if err != nil {
		return res, errors.Wrap(err, "create request")
	}

	{
		type bitset = [1]uint8
		var satisfied bitset
		{

			switch err := c.securityBearerToken(ctx, GetInstanceMetricsByUUIDOperation, r); {
			case err == nil: // if NO error
				satisfied[0] |= 1 << 0
			case errors.Is(err, ogenerrors.ErrSkipClientSecurity):
				// Skip this security.
			default:
				return res, errors.Wrap(err, "security \"BearerToken\"")
			}
		}

		if ok := func() bool {
		nextRequirement:
			for _, requirement := range []bitset{
				{0b00000001},
			} {
				for i, mask := range requirement {
					if satisfied[i]&mask != mask {
						continue nextRequirement
					}
				}
				return true
			}
			return false
		}(); !ok {
			return res, ogenerrors.ErrSecurityRequirementIsNotSatisfied
		}
	}

	resp, err := c.cfg.Client.Do(r)
	if err != nil {
		return res, errors.Wrap(err, "do request")
	}
	defer resp.Body.Close()

	result, err := decodeGetInstanceMetricsByUUIDResponse(resp)
	if err != nil {
		return res, errors.Wrap(err, "decode response")
	}

	return result, nil
}

// GetInstances invokes GetInstances operation.
//
// Get one or many instances with their current status and configuration.
//
//	It's possible to filter this list by name or UUID.
//
// GET /v1/instances
func (c *Client) GetInstances(ctx context.Context, params GetInstancesParams) (*GetInstancesResponse, error) {
	res, err := c.sendGetInstances(ctx, params)
	return res, err
}

func (c *Client) sendGetInstances(ctx context.Context, params GetInstancesParams) (res *GetInstancesResponse, err error) {

	u := uri.Clone(c.requestURL(ctx))
	var pathParts [1]string
	pathParts[0] = "/v1/instances"
	uri.AddPathParts(u, pathParts[:]...)

	q := uri.NewQueryEncoder()
	{
		// Encode "uuid" parameter.
		cfg := uri.QueryParameterEncodingConfig{
			Name:    "uuid",
			Style:   uri.QueryStyleForm,
			Explode: true,
		}

		if err := q.EncodeParam(cfg, func(e uri.Encoder) error {
			if val, ok := params.UUID.Get(); ok {
				return e.EncodeValue(conv.StringToString(val))
			}
			return nil
		}); err != nil {
			return res, errors.Wrap(err, "encode query")
		}
	}
	{
		// Encode "name" parameter.
		cfg := uri.QueryParameterEncodingConfig{
			Name:    "name",
			Style:   uri.QueryStyleForm,
			Explode: true,
		}

		if err := q.EncodeParam(cfg, func(e uri.Encoder) error {
			if val, ok := params.Name.Get(); ok {
				return e.EncodeValue(conv.StringToString(val))
			}
			return nil
		}); err != nil {
			return res, errors.Wrap(err, "encode query")
		}
	}
	{
		// Encode "details" parameter.
		cfg := uri.QueryParameterEncodingConfig{
			Name:    "details",
			Style:   uri.QueryStyleForm,
			Explode: true,
		}

		if err := q.EncodeParam(cfg, func(e uri.Encoder) error {
			if val, ok := params.Details.Get(); ok {
				return e.EncodeValue(conv.BoolToString(val))
			}
			return nil
		}); err != nil {
			return res, errors.Wrap(err, "encode query")
		}
	}
	{
		// Encode "metrics" parameter.
		cfg := uri.QueryParameterEncodingConfig{
			Name:    "metrics",
			Style:   uri.QueryStyleForm,
			Explode: true,
		}

		if err := q.EncodeParam(cfg, func(e uri.Encoder) error {
			if val, ok := params.Metrics.Get(); ok {
				return e.EncodeValue(conv.BoolToString(val))
			}
			return nil
		}); err != nil {
			return res, errors.Wrap(err, "encode query")
		}
	}
	u.RawQuery = q.Values().Encode()

	r, err := ht.NewRequest(ctx, "GET", u)
	if err != nil {
		return res, errors.Wrap(err, "create request")
	}

	{
		type bitset = [1]uint8
		var satisfied bitset
		{

			switch err := c.securityBearerToken(ctx, GetInstancesOperation, r); {
			case err == nil: // if NO error
				satisfied[0] |= 1 << 0
			case errors.Is(err, ogenerrors.ErrSkipClientSecurity):
				// Skip this security.
			default:
				return res, errors.Wrap(err, "security \"BearerToken\"")
			}
		}

		if ok := func() bool {
		nextRequirement:
			for _, requirement := range []bitset{
				{0b00000001},
			} {
				for i, mask := range requirement {
					if satisfied[i]&mask != mask {
						continue nextRequirement
					}
				}
				return true
			}
			return false
		}(); !ok {
			return res, ogenerrors.ErrSecurityRequirementIsNotSatisfied
		}
	}

	resp, err := c.cfg.Client.Do(r)
	if err != nil {
		return res, errors.Wrap(err, "do request")
	}
	defer resp.Body.Close()

	result, err := decodeGetInstancesResponse(resp)
	if err != nil {
		return res, errors.Wrap(err, "decode response")
	}

	return result, nil
}

// StartInstanceByUUID invokes StartInstanceByUUID operation.
//
// Starts previously stopped instance by its UUID or does nothing if the
//
//	instance is already running.
//
// PUT /v1/instances/{uuid}/start
func (c *Client) StartInstanceByUUID(ctx context.Context, params StartInstanceByUUIDParams) (*StartInstanceResponse, error) {
	res, err := c.sendStartInstanceByUUID(ctx, params)
	return res, err
}

func (c *Client) sendStartInstanceByUUID(ctx context.Context, params StartInstanceByUUIDParams) (res *StartInstanceResponse, err error) {

	u := uri.Clone(c.requestURL(ctx))
	var pathParts [3]string
	pathParts[0] = "/v1/instances/"
	{
		// Encode "uuid" parameter.
		e := uri.NewPathEncoder(uri.PathEncoderConfig{
			Param:   "uuid",
			Style:   uri.PathStyleSimple,
			Explode: false,
		})
		if err := func() error {
			return e.EncodeValue(conv.StringToString(params.UUID))
		}(); err != nil {
			return res, errors.Wrap(err, "encode path")
		}
		encoded, err := e.Result()
		if err != nil {
			return res, errors.Wrap(err, "encode path")
		}
		pathParts[1] = encoded
	}
	pathParts[2] = "/start"
	uri.AddPathParts(u, pathParts[:]...)

	r, err := ht.NewRequest(ctx, "PUT", u)
	if err != nil {
		return res, errors.Wrap(err, "create request")
	}

	{
		type bitset = [1]uint8
		var satisfied bitset
		{

			switch err := c.securityBearerToken(ctx, StartInstanceByUUIDOperation, r); {
			case err == nil: // if NO error
				satisfied[0] |= 1 << 0
			case errors.Is(err, ogenerrors.ErrSkipClientSecurity):
				// Skip this security.
			default:
				return res, errors.Wrap(err, "security \"BearerToken\"")
			}
		}

		if ok := func() bool {
		nextRequirement:
			for _, requirement := range []bitset{
				{0b00000001},
			} {
				for i, mask := range requirement {
					if satisfied[i]&mask != mask {
						continue nextRequirement
					}
				}
				return true
			}
			return false
		}(); !ok {
			return res, ogenerrors.ErrSecurityRequirementIsNotSatisfied
		}
	}

	resp, err := c.cfg.Client.Do(r)
	if err != nil {
		return res, errors.Wrap(err, "do request")
	}
	defer resp.Body.Close()

	result, err := decodeStartInstanceByUUIDResponse(resp)
	if err != nil {
		return res, errors.Wrap(err, "decode response")
	}

	return result, nil
}

// StopInstanceByUUID invokes StopInstanceByUUID operation.
//
// Stops a running instance by its UUID or does nothing if the instance is
//
//	already stopped.
//
// PUT /v1/instances/{uuid}/stop
func (c *Client) StopInstanceByUUID(ctx context.Context, params StopInstanceByUUIDParams) (*StopInstanceResponse, error) {
	res, err := c.sendStopInstanceByUUID(ctx, params)
	return res, err
}

func (c *Client) sendStopInstanceByUUID(ctx context.Context, params StopInstanceByUUIDParams) (res *StopInstanceResponse, err error) {

	u := uri.Clone(c.requestURL(ctx))
	var pathParts [3]string
	pathParts[0] = "/v1/instances/"
	{
		// Encode "uuid" parameter.
		e := uri.NewPathEncoder(uri.PathEncoderConfig{
			Param:   "uuid",
			Style:   uri.PathStyleSimple,
			Explode: false,
		})
		if err := func() error {
			return e.EncodeValue(conv.StringToString(params.UUID))
		}(); err != nil {
			return res, errors.Wrap(err, "encode path")
		}
		encoded, err := e.Result()
		if err != nil {
			return res, errors.Wrap(err, "encode path")
		}
		pathParts[1] = encoded
	}
	pathParts[2] = "/stop"
	uri.AddPathParts(u, pathParts[:]...)

	q := uri.NewQueryEncoder()
	{
		// Encode "force" parameter.
		cfg := uri.QueryParameterEncodingConfig{
			Name:    "force",
			Style:   uri.QueryStyleForm,
			Explode: true,
		}

		if err := q.EncodeParam(cfg, func(e uri.Encoder) error {
			if val, ok := params.Force.Get(); ok {
				return e.EncodeValue(conv.BoolToString(val))
			}
			return nil
		}); err != nil {
			return res, errors.Wrap(err, "encode query")
		}
	}
	{
		// Encode "drain_timeout_ms" parameter.
		cfg := uri.QueryParameterEncodingConfig{
			Name:    "drain_timeout_ms",
			Style:   uri.QueryStyleForm,
			Explode: true,
		}

		if err := q.EncodeParam(cfg, func(e uri.Encoder) error {
			if val, ok := params.DrainTimeoutMs.Get(); ok {
				return e.EncodeValue(conv.Uint64ToString(val))
			}
			return nil
		}); err != nil {
			return res, errors.Wrap(err, "encode query")
		}
	}
	u.RawQuery = q.Values().Encode()

	r, err := ht.NewRequest(ctx, "PUT", u)
	if err != nil {
		return res, errors.Wrap(err, "create request")
	}

	{
		type bitset = [1]uint8
		var satisfied bitset
		{

			switch err := c.securityBearerToken(ctx, StopInstanceByUUIDOperation, r); {
			case err == nil: // if NO error
				satisfied[0] |= 1 << 0
			case errors.Is(err, ogenerrors.ErrSkipClientSecurity):
				// Skip this security.
			default:
				return res, errors.Wrap(err, "security \"BearerToken\"")
			}
		}

		if ok := func() bool {
		nextRequirement:
			for _, requirement := range []bitset{
				{0b00000001},
			} {
				for i, mask := range requirement {
					if satisfied[i]&mask != mask {
						continue nextRequirement
					}
				}
				return true
			}
			return false
		}(); !ok {
			return res, ogenerrors.ErrSecurityRequirementIsNotSatisfied
		}
	}

	resp, err := c.cfg.Client.Do(r)
	if err != nil {
		return res, errors.Wrap(err, "do request")
	}
	defer resp.Body.Close()

	result, err := decodeStopInstanceByUUIDResponse(resp)
	if err != nil {
		return res, errors.Wrap(err, "decode response")
	}

	return result, nil
}

// StopInstances invokes StopInstances operation.
//
// Stops one or more running instance by their UUID(s) or name(s) or does
//
//	nothing if the instance is already stopped.
//
// PUT /v1/instances/stop
func (c *Client) StopInstances(ctx context.Context, request []StopInstancesRequestID, params StopInstancesParams) (*StopInstanceResponse, error) {
	res, err := c.sendStopInstances(ctx, request, params)
	return res, err
}

func (c *Client) sendStopInstances(ctx context.Context, request []StopInstancesRequestID, params StopInstancesParams) (res *StopInstanceResponse, err error) {

	u := uri.Clone(c.requestURL(ctx))
	var pathParts [1]string
	pathParts[0] = "/v1/instances/stop"
	uri.AddPathParts(u, pathParts[:]...)

	q := uri.NewQueryEncoder()
	{
		// Encode "force" parameter.
		cfg := uri.QueryParameterEncodingConfig{
			Name:    "force",
			Style:   uri.QueryStyleForm,
			Explode: true,
		}

		if err := q.EncodeParam(cfg, func(e uri.Encoder) error {
			if val, ok := params.Force.Get(); ok {
				return e.EncodeValue(conv.BoolToString(val))
			}
			return nil
		}); err != nil {
			return res, errors.Wrap(err, "encode query")
		}
	}
	{
		// Encode "drain_timeout_ms" parameter.
		cfg := uri.QueryParameterEncodingConfig{
			Name:    "drain_timeout_ms",
			Style:   uri.QueryStyleForm,
			Explode: true,
		}

		if err := q.EncodeParam(cfg, func(e uri.Encoder) error {
			if val, ok := params.DrainTimeoutMs.Get(); ok {
				return e.EncodeValue(conv.Uint64ToString(val))
			}
			return nil
		}); err != nil {
			return res, errors.Wrap(err, "encode query")
		}
	}
	u.RawQuery = q.Values().Encode()

	r, err := ht.NewRequest(ctx, "PUT", u)
	if err != nil {
		return res, errors.Wrap(err, "create request")
	}
	if err := encodeStopInstancesRequest(request, r); err != nil {
		return res, errors.Wrap(err, "encode request")
	}

	{
		type bitset = [1]uint8
		var satisfied bitset
		{

			switch err := c.securityBearerToken(ctx, StopInstancesOperation, r); {
			case err == nil: // if NO error
				satisfied[0] |= 1 << 0
			case errors.Is(err, ogenerrors.ErrSkipClientSecurity):
				// Skip this security.
			default:
				return res, errors.Wrap(err, "security \"BearerToken\"")
			}
		}

		if ok := func() bool {
		nextRequirement:
			for _, requirement := range []bitset{
				{0b00000001},
			} {
				for i, mask := range requirement {
					if satisfied[i]&mask != mask {
						continue nextRequirement
					}
				}
				return true
			}
			return false
		}(); !ok {
			return res, ogenerrors.ErrSecurityRequirementIsNotSatisfied
		}
	}

	resp, err := c.cfg.Client.Do(r)
	if err != nil {
		return res, errors.Wrap(err, "do request")
	}
	defer resp.Body.Close()

	result, err := decodeStopInstancesResponse(resp)
	if err != nil {
		return res, errors.Wrap(err, "decode response")
	}

	return result, nil
}

// WaitInstanceByUUID invokes WaitInstanceByUUID operation.
//
// Waits for an instance to reach a certain state by its UUID.
//
//	If the instance is already in the desired state, the request will return
//	immediately.  If the instance is not in the desired state, the request will
//	block until the instance reaches the desired state or the timeout is
//	reached.  If the timeout is reached, the request will fail with an error.
//	If the timeout is -1, the request will block indefinitely until the
//	instance reaches the desired state.
//
// GET /v1/instances/{uuid}/wait
func (c *Client) WaitInstanceByUUID(ctx context.Context, params WaitInstanceByUUIDParams) (*WaitInstanceResponse, error) {
	res, err := c.sendWaitInstanceByUUID(ctx, params)
	return res, err
}

func (c *Client) sendWaitInstanceByUUID(ctx context.Context, params WaitInstanceByUUIDParams) (res *WaitInstanceResponse, err error) {

	u := uri.Clone(c.requestURL(ctx))
	var pathParts [3]string
	pathParts[0] = "/v1/instances/"
	{
		// Encode "uuid" parameter.
		e := uri.NewPathEncoder(uri.PathEncoderConfig{
			Param:   "uuid",
			Style:   uri.PathStyleSimple,
			Explode: false,
		})
		if err := func() error {
			return e.EncodeValue(conv.StringToString(params.UUID))
		}(); err != nil {
			return res, errors.Wrap(err, "encode path")
		}
		encoded, err := e.Result()
		if err != nil {
			return res, errors.Wrap(err, "encode path")
		}
		pathParts[1] = encoded
	}
	pathParts[2] = "/wait"
	uri.AddPathParts(u, pathParts[:]...)

	q := uri.NewQueryEncoder()
	{
		// Encode "state" parameter.
		cfg := uri.QueryParameterEncodingConfig{
			Name:    "state",
			Style:   uri.QueryStyleForm,
			Explode: true,
		}

		if err := q.EncodeParam(cfg, func(e uri.Encoder) error {
			if val, ok := params.State.Get(); ok {
				return e.EncodeValue(conv.StringToString(string(val)))
			}
			return nil
		}); err != nil {
			return res, errors.Wrap(err, "encode query")
		}
	}
	{
		// Encode "timeout_ms" parameter.
		cfg := uri.QueryParameterEncodingConfig{
			Name:    "timeout_ms",
			Style:   uri.QueryStyleForm,
			Explode: true,
		}

		if err := q.EncodeParam(cfg, func(e uri.Encoder) error {
			if val, ok := params.TimeoutMs.Get(); ok {
				return e.EncodeValue(conv.Int64ToString(val))
			}
			return nil
		}); err != nil {
			return res, errors.Wrap(err, "encode query")
		}
	}
	u.RawQuery = q.Values().Encode()

	r, err := ht.NewRequest(ctx, "GET", u)
	if err != nil {
		return res, errors.Wrap(err, "create request")
	}

	{
		type bitset = [1]uint8
		var satisfied bitset
		{

			switch err := c.securityBearerToken(ctx, WaitInstanceByUUIDOperation, r); {
			case err == nil: // if NO error
				satisfied[0] |= 1 << 0
			case errors.Is(err, ogenerrors.ErrSkipClientSecurity):
				// Skip this security.
			default:
				return res, errors.Wrap(err, "security \"BearerToken\"")
			}
		}

		if ok := func() bool {
		nextRequirement:
			for _, requirement := range []bitset{
				{0b00000001},
			} {
				for i, mask := range requirement {
					if satisfied[i]&mask != mask {
						continue nextRequirement
					}
				}
				return true
			}
			return false
		}(); !ok {
			return res, ogenerrors.ErrSecurityRequirementIsNotSatisfied
		}
	}

	resp, err := c.cfg.Client.Do(r)
	if err != nil {
		return res, errors.Wrap(err, "do request")
	}
	defer resp.Body.Close()

	result, err := decodeWaitInstanceByUUIDResponse(resp)
	if err != nil {
		return res, errors.Wrap(err, "decode response")
	}

	return result, nil
}

// WaitInstances invokes WaitInstances operation.
//
// Waits for an instance to reach a certain state by its UUID or name.
//
//	If the instance is already in the desired state, the request will return
//	immediately.  If the instance is not in the desired state, the request will
//	block until the instance reaches the desired state or the timeout is
//	reached.  If the timeout is reached, the request will fail with an error.
//	If the timeout is -1, the request will block indefinitely until the
//	instance reaches the desired state.
//
// GET /v1/instances/wait
func (c *Client) WaitInstances(ctx context.Context, request *WaitInstancesRequest) (*WaitInstanceResponse, error) {
	res, err := c.sendWaitInstances(ctx, request)
	return res, err
}

func (c *Client) sendWaitInstances(ctx context.Context, request *WaitInstancesRequest) (res *WaitInstanceResponse, err error) {

	u := uri.Clone(c.requestURL(ctx))
	var pathParts [1]string
	pathParts[0] = "/v1/instances/wait"
	uri.AddPathParts(u, pathParts[:]...)

	r, err := ht.NewRequest(ctx, "GET", u)
	if err != nil {
		return res, errors.Wrap(err, "create request")
	}
	if err := encodeWaitInstancesRequest(request, r); err != nil {
		return res, errors.Wrap(err, "encode request")
	}

	{
		type bitset = [1]uint8
		var satisfied bitset
		{

			switch err := c.securityBearerToken(ctx, WaitInstancesOperation, r); {
			case err == nil: // if NO error
				satisfied[0] |= 1 << 0
			case errors.Is(err, ogenerrors.ErrSkipClientSecurity):
				// Skip this security.
			default:
				return res, errors.Wrap(err, "security \"BearerToken\"")
			}
		}

		if ok := func() bool {
		nextRequirement:
			for _, requirement := range []bitset{
				{0b00000001},
			} {
				for i, mask := range requirement {
					if satisfied[i]&mask != mask {
						continue nextRequirement
					}
				}
				return true
			}
			return false
		}(); !ok {
			return res, ogenerrors.ErrSecurityRequirementIsNotSatisfied
		}
	}

	resp, err := c.cfg.Client.Do(r)
	if err != nil {
		return res, errors.Wrap(err, "do request")
	}
	defer resp.Body.Close()

	result, err := decodeWaitInstancesResponse(resp)
	if err != nil {
		return res, errors.Wrap(err, "decode response")
	}

	return result, nil
}
