name: sync

on:
  workflow_dispatch:
    inputs:
      channel:
        default: prod-stable
        description: |
          The name of the release channel.
          One of: [prod-stable, prod-staging]

# Automatically cancel in-progress actions on the same branch
concurrency:
  group: ${{ github.workflow }}-${{ github.event_name == 'pull_request_target' && github.head_ref || github.ref }}
  cancel-in-progress: true

permissions:
  contents: write

jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
      with:
        ref: ${{ inputs.channel }}

    - name: Reset promotion branch
      shell: bash
      run: |
        git fetch origin ${{ inputs.channel }}:${{ inputs.channel }}
        git reset --hard ${{ inputs.channel }}

    - name: Generate
      shell: bash
      env:
        CHANNEL: ${{ inputs.channel }}
      run: |
        make generate

    - name: Commit and push
      id: commit
      run: |
        git config user.name "Unikraft Bot"
        git config user.email "monkey@unikraft.io"

        BRANCH="sync/$(date +'%Y%m%d%H%M%S')"
        git checkout -b "${BRANCH}"

        git add .
        git commit -s -m "sync: Update Go SDK from OpenAPI spec"
        git push -u origin "${BRANCH}"

        echo "branch=${BRANCH}" >>"${GITHUB_OUTPUT}"

    - name: Create pull request
      uses: peter-evans/create-pull-request@v6
      with:
        token: ${{ secrets.GH_PAT }}
        base: ${{ steps.commit.outputs.branch }}
        title: "sync: Update Go SDK from OpenAPI spec"
        branch: ${{ inputs.channel }}
